### ISSUE TITLE
2 Guards in Fairbreeze Village

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#1007]
Shouldn't they have a waypoints?

![WoWScrnShot_010422_215722](https://user-images.githubusercontent.com/6240049/148116583-b8012c84-fb5e-4d83-9ed4-a8b574871d23.jpg)

**Comment by AnonXS** [comment]
Can we also have some written text with guids not just a screenshot?

**Comment by al3xc1985** [comment]
I am sorry, I let the report in a fast run, cause I left to work. When I get home tonight ubwill have your guids

**Comment by al3xc1985** [comment]
@AnonXS first post updated with guids...
Judging by the point where they are spawned, they might be involved in a small event with locals or Magistrix Landra, dunno. Just a thought
