### ISSUE TITLE
Event?

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#1015]
@AnonXS or @killerwife  can u check this video pls at minute 5 and  tell me please what event is that and if u have it implemented?

https://www.youtube.com/watch?v=9MYD49jdDIM

**Comment by AnonXS** [comment]
... thats sourge invasion, if its implemented the exact same way, idk. but we have that now...

**Comment by al3xc1985** [comment]
I was just asking @AnonXS cause I didn't catched all the scourge invasion event.. well ty

**Comment by insunaa** [comment]
That is as AnonXS said indeed the scourge invasion and we have it implemented.  As we have it right now there are fewer mobs spawned than shown in this video, but I also don't know how credible that video is as evidence to increase the number of mobs. We still spawn a very considerable number of mobs.
