### ISSUE TITLE
[Bug] Bleeding Hollow Necrolyte

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#1018]
Npc = 19422 have a summoning spell that is not working anymore after last implementations... I tested it on vengeance and private also
@killerwife

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/156642495-97ae2576-7513-49b9-a13e-33c8389b5215.png)

he uses friendly corpses i think, not the player corpse.

**Comment by al3xc1985** [comment]
thank you
