### ISSUE TITLE
Hellfire Sentry's don't pull together

### ISSUE THREAD

**Issue by Saben65** [cmangos/tbc-db#103]
Just before the final boss in Ramparts, the two sentries should pull together. Currently they can be pulled separately. https://www.youtube.com/watch?v=iB1mddy98-Y&t=7m

**Suggested Fix:**
```SQL
DELETE FROM `creature_linking` WHERE `guid` IN (63011);
INSERT INTO `creature_linking` (`guid`,`master_guid`,`flag`) VALUES
(63011,63012,3);
```

**Comment by Saltgurka** [comment]
Solved here: https://github.com/cmangos/tbc-db/commit/262c2b42c40db50fac23c072f27bca09a2f6afb1

We're working on exporting everything in the following days, so there should be no duplicate fixes anymore :)
