### ISSUE TITLE
Steamvaults Coilfang Engineers spawn inside terrain

### ISSUE THREAD

**Issue by Saben65** [cmangos/tbc-db#104]
See https://github.com/TrinityCore/TrinityCore/issues/16104. Their equip is also incorrect, but I will fix that at a later time since it likely has to be added to the item database.

**Suggested Fix:**
```SQL
UPDATE `creature` SET `position_x`=-5.298958, `position_y`=-131.3911, `position_z`=-21.17339, `orientation`=4.817109 WHERE `guid`= 12686;
UPDATE `creature` SET `position_x`=-21.93356, `position_y`=-126.7303, `position_z`=-21.71569, `orientation`=4.939282 WHERE `guid`= 12687;

```

**Comment by MantisLord** [comment]
Any progress on the full instance respawn and missing movement? I think this is still needed in addition to this fix and I see in the Trinity issue you mentioned you may work on it.

**Comment by Saben65** [comment]
I did a pass and gave everything the correct equips and emotes. As for the pathing I could never get it to look right because 'creature_formations' was pretty whonky. IIRC it is even more borked on cmangos, but I could give it a look. 

I thought I submitted my fixes somewhere, so I will have to go through my history and see.

Are the majority on the dungeon fixes ported from vengeance done? I have noticed a few things that need fixing but didn't want to spend time on them they are still pending fixes from vengeance.

**Comment by MantisLord** [comment]
You're generally pretty safe, however I do have a Shattered Halls rework in progress, so you may want to avoid that for now. Ramparts and Blood Furnace also have some unexported files which we should be getting to relatively soon.
If you want more specifics, feel free to join irc.irzon.net #vengeancewow and we can provide you with anything outstanding that is awaiting export so you don't repeat any work.
