### ISSUE TITLE
Some creature data problems

### ISSUE THREAD

**Issue by aleigood** [cmangos/tbc-db#1054]
The creature stood still:
Entry: 21423 - linked to Toshley's Station Attack Event <https://github.com/cmangos/tbc-db/commit/a6299f1bee56d22c20ced7c0df13db229980a488> -> deserves its own issue and research.

Nearby creatures stood still:
- [x] .go xyz 7893.2 -6665.124 43.055935 530 - (entry  16307)
- [x] .go xyz 8751.087891 -7147.976562 35.227638 530 - Entry:15658 Guid:56125 - https://youtu.be/2AEHXqSM-R8?t=6
- [x] .go xyz 7557.8369 -6190.772949 19.312061 530 (entry 16350,16353)

- [x] Wrong faction:
Entry:21055 guid:73961 

```
[0] OBJECT_FIELD_ENTRY: 21063
[0] UNIT_FIELD_FACTIONTEMPLATE: 188/2.63E-43 (188)
```

**Comment by aleigood** [comment]
newly added:

.go xyz 7887.459473 -6188.740 19.9420 530

**Comment by AnonXS** [comment]
Please open a new issue [here](https://github.com/cmangos/issues/issues) for more Ghostland fixes, atleast keep it separeted by zone, else we could just write all issues regarding cmangos into one issue... you know what i mean.
