### ISSUE TITLE
Quest start scripts can have a cooldown period

### ISSUE THREAD

**Issue by Nytanath** [cmangos/tbc-db#1055]
Not exactly an issue, but a mechanic that we currently don't support (as far as I could tell): scripts that happen on quest accept can have a cooldown period before they can be re-activated. Specially when the NPC does not lose the questgiver npcflag.

One example I found is [Cave Mushrooms](https://tbc.wowhead.com/quest=947/cave-mushrooms):

https://user-images.githubusercontent.com/99603810/162767248-d206ebda-a959-46eb-9c5a-fafd9455c086.mp4

Notice that it took me three attempts to trigger this script again, even when I accepted the quest while the previous event was already finished. Script cooldown for this one seems to be around 40-50 seconds, while the event itself lasts roughly 5 seconds.

**Comment by killerwife** [comment]
Yes we do :) if you make the script run for 40-50 seconds, its unique to run only once. Add a condition check at the complete end, something trivial and it will not run again in that time.

**Comment by Nytanath** [comment]
Ooh you mean adding a dummy entry to the dbscript that makes the script long enough? Yeah that makes sense, could use something like add npcflag questgiver since the npc already has it. Got it, thanks!
