### ISSUE TITLE
Bog Overlords don't have stealth detection.

### ISSUE THREAD

**Issue by Saben65** [cmangos/tbc-db#11]
>These guys have stealth detection.

http://www.wowhead.com/npc=21694/bog-overlord#comments:id=210063

(I have also verified it on retail)

Suggested Fix
```SQL
-- Add stealth detection to Bog Overlords
UPDATE `creature_template_addon` SET `auras`='18950' WHERE `entry`=21694;
```

**Comment by killerwife** [comment]
Closed in https://github.com/cmangos/tbc-db/commit/6ba206588a58d7fb021d7d27353d364f8b630297
