### ISSUE TITLE
[Kara] Emote fix for Spectral Retainers and Phantom Attendants

### ISSUE THREAD

**Issue by Saben65** [cmangos/tbc-db#180]
[Spectral Retainers](http://www.wowhead.com/npc=16410/spectral-retainer) and [Phantom attendants](http://www.wowhead.com/npc=16406/phantom-attendant) should not be dancing like the [Phantom Guests](http://www.wowhead.com/npc=16409/phantom-guest). Instead, they should be talking amongst themselves and occasionally laughing. I couldn't figure out where to handle them randomly talking & laughing (they do so on the top floor but not the bottom, so I think it must be tied to their GUIDs not entry). Below is the fix to get them to stop dancing.

```sql
-- Remove dance emote from Phantom Attendants and Spectral Retainers
DELETE FROM `creature_addon` WHERE `guid` IN (85099,85095,85096,85097,85098,85175,85118,85119,85120,85176,85111,85106,85189) AND `emote`=400;
```

**Comment by MantisLord** [comment]
Thanks, I've been meaning to fix this for awhile. It appears the others actually use creature_movement with dbscripts to perform the random emotes.
