### ISSUE TITLE
386_UDB-179_creature_template.sql missing 612 creature_equip_template

### ISSUE THREAD

**Issue by stan84** [cmangos/tbc-db#19]
to fix it i propose:

INSERT INTO `mangos`.`creature_equip_template` (`entry`, `equipentry1`, `equipentry2`, `equipentry3`) VALUES ('612', '34311', '0', '0');

**Comment by killerwife** [comment]
1. never specify schema name pls
2. I have 430 incoming updates in terms of syncing so it might be fixed with those automatically. It just takes a lot of time to do properly.

**Comment by stan84** [comment]
ok i will not, just like to help. Core generating file about 200kb of errors, sry.

**Comment by killerwife** [comment]
Feel free to do some fixing, I just wanted to warn you because tbc-db public is currently in a dilapilated state and I did not want to waste your time :)
I was waiting for some core patches before I could continue, will resume next week.

**Comment by Saltgurka** [comment]
Solved with https://github.com/cmangos/tbc-db/commit/bf328a4cf4405e8ae3c4e2addbeb5d7c71d01c58?
