### ISSUE TITLE
Error while importing update

### ISSUE THREAD

**Issue by Blumfield** [cmangos/tbc-db#2]
Greetings, I faced some error while importing update (using the windows bat) I checked and it appears the table wpguid exist on the wiki but not in the actual core(?) i'm somewhat confused, I didin't keep the error log but you can see what sql were affected here https://github.com/Blumfield/tbc-db/commit/878069d71e4039521a3ff7f6fea8e60e696d0e6e

**Comment by killerwife** [comment]
2 things, I forgot to add the comments collumn to loot templates and then you are right about the WPGuid thing. I forgot to remove them in the big commit. Thx for notifying me about it.

**Comment by killerwife** [comment]
Closing this, fix will be pushed in next 10 minutes.
