### ISSUE TITLE
NPC Heroic Class different from Normal Class

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/tbc-db#22]
Values are based on Assuptions - i checked the spells, appearance and name to determine the right class out of the 2 possibilities

17377_keli_dan_the_breaker
UPDATE creature_template SET UnitClass = 8 WHERE entry = 17377;

18093_tarren_mill_protector
UPDATE creature_template SET UnitClass = 2 WHERE entry = 18093;

18094_tarren_mill_lookout
UPDATE creature_template SET UnitClass = 2 WHERE entry = 18094;

20322_unliving_sorcerer
UPDATE creature_template SET UnitClass = 8 WHERE entry = 20322;

25547_coilskar_witch
UPDATE creature_template SET UnitClass = 8 WHERE entry = 25547;

**Comment by killerwife** [comment]
Fixed in latest commit.
