### ISSUE TITLE
181606_haaleshi_altar

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/tbc-db#23]
Fix the quest http://www.wowhead.com/quest=9418/avruus-orb
Gossip for the Altar

Source: https://gist.github.com/shlainn/3423641#file-gistfile1-txt

UPDATE `gameobject_template` SET `type`='2',`data0`='1656',`data1`='9418',`data3`='10219' WHERE (`entry`='181606');

**Comment by Saben65** [comment]
The quest appears to work fine as is.

**Comment by MantisLord** [comment]
I also don't seem to have any problem with this quest. 
gameobject_template data is not to be modified in this scenario.
