### ISSUE TITLE
[Quest 9440] Little Morsels

### ISSUE THREAD

**Issue by ulfgebhardt** [cmangos/tbc-db#24]
Fix for quest http://www.wowhead.com/quest=9440/deprecated-little-morsels
What i noticed is weird: Wohead states Added in patch 3.3.0.10772
Is this a TBC quest? I think so!

Make Cages usable to enable them to Open and be able to LOS and do quest Objective

181624_tarantula_cage

REPLACE INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `faction`, `flags`, `size`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`, `data8`, `data9`, `data10`, `data11`, `data12`, `data13`, `data14`, `data15`, `data16`, `data17`, `data18`, `data19`, `data20`, `data21`, `data22`, `data23`, `mingold`, `maxgold`, `ScriptName`) VALUES (181624, 0, 1787, 'Tarantula Cage', '', '', 0, 0, 1.75, 0, 0, 1966080, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');

181625_jaguar_crocolisk_cage

REPLACE INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `faction`, `flags`, `size`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`, `data8`, `data9`, `data10`, `data11`, `data12`, `data13`, `data14`, `data15`, `data16`, `data17`, `data18`, `data19`, `data20`, `data21`, `data22`, `data23`, `mingold`, `maxgold`, `ScriptName`) VALUES (181625, 0, 4154, 'Jaguar - Crocolisk Cage', '', '', 0, 0, 1, 0, 0, 1966080, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');

**Comment by bdebaere** [comment]
Seeing as how the comments start as early as patch 2.0.5, I think you are right to assume this quest was already added before 3.3.0.10772.

**Comment by Grz3s** [comment]
You should **never ever** change WDB **legit** data ...
all you reQ. to fix this quest was already added into wotlk...
https://github.com/cmangos/mangos-wotlk/commit/a4312188b679b33c2db373d2d71ef24496153072
Poke @killerwife

**Comment by killerwife** [comment]
Since the patch mentioned by @Grz3s is in mangos-tbc, closing this.
