### ISSUE TITLE
Oronok the torn-heart not casting spells

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#31]
Oronok - http://www.wowhead.com/npc=21183/oronok-torn-heart
should cast Chain Lightning
Evidence - https://youtu.be/uIlgWOV-_oQ

@Grz3s do you know spell ID?

**Comment by Grz3s** [comment]
16006

**Comment by killerwife** [comment]
Amazing. Will add commit to both tbc-db and wotlk-db.

**Comment by killerwife** [comment]
('2118301', '21183', '0', '0', '100', '1', '0', '0', '10000', '15000', '11', '16006', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Oronok Torn-Heart - Cast Chain Lightning'),

Added repeatability with 10s to 15s timer. Any objections?

**Comment by Grz3s** [comment]
'6700','11200','18100','24900'

**Comment by killerwife** [comment]
Where did you get that?

**Comment by Grz3s** [comment]
this spell is used also by another creature...  and data comes from x-saviors combat logs (its official)
