### ISSUE TITLE
Civilian flag needs makeover

### ISSUE THREAD

**Issue by Warlockbugs** [cmangos/tbc-db#321]
Bringing to your attention: https://github.com/cmangos/mangos-tbc/commit/2f739a260b4533942c6319a9126c954166d9c8e4

Previous mixed "Civilian" flag was split into "No aggro on sight" and new "Civilian". New civilian is used to signal zone under attack, call guards or for custom old-schoolish honor system (DHK).

Close this issue when you are satisfied with conversion results.

**Comment by AnonXS** [comment]
Working as intended with this ExtraFlag change, Civilians summon Guards on Aggro due to core scripted usage of the Guard Summoning Spell. Working as intended.
