### ISSUE TITLE
Netherwing Questline 

### ISSUE THREAD

**Issue by berserkingyadis** [cmangos/tbc-db#330]
I am investigating the Netherwing questline at the moment and will post my findings in here. I will edit my progress in this issue.

For people who want to help, this page covers the quest flow of the entire chain: https://wow.gamepedia.com/Netherwing

## General Observations
- Upon completing a quest, the npc dialogue sometimes does not show the "Rewards: exp, gold" text, just the usual "thank you" message.
- Elite mobs hit very hard, got 12k damage from a lvl72 Dragonmaw Ascendant ( id = 22253 ), should do less [src](http://www.wowhead.com/npc=22253/dragonmaw-ascendant#comments)

# HATED TO NEUTRAL
## Quest: Kindness (ID = 10804 )

- [x] The drakes are descending and ascending very slowly. Their speed in general is pretty low.
- [ ] When Mordenai (entry = 22113, guid = 77645) is fighting, his quest marker should disappear. It doesnt.
![1s](https://user-images.githubusercontent.com/9959527/32121057-424c8e2e-bb5b-11e7-8151-a8e0f484fb68.jpg)
## Quest: Seek out Neltharaku
- Neltharaku (entry = 21657 guid = 75654)
-  all ok
## Quest: Neltharaku's Tale
- all ok
## Quest: Inflitrating Dragonmaw Fortress
- [x] This drake is flying while on the ground (GUID: 75828) (Set InhabitType, Recheck with Script and Add potential missing sleeping aura/script relation)
![3s](https://user-images.githubusercontent.com/9959527/32121140-9bf614b8-bb5b-11e7-81af-bc3b454afc83.jpg)

## Quest: To Netherwing Ledge!
- [x] The dragonmaw peons (id = 22252 ) have about 6.5k hp, but they should have ~3.2k (https://wow.gamepedia.com/Dragonmaw_Peon)  - **FIXED IN https://github.com/cmangos/tbc-db/commit/e6623c09f6fb43d400586c0d443ddbc16fea70e0** 

## Quest: The Force of Neltharaku
- [x] Using the item "Enchanted Nethervine Crystal" (id = 31652 ) on the drakes should fire a projectile (like in https://youtu.be/negt5rQFBoQ?t=35) but it fires nothing
- [x] Can use item 31652 repeatedly on already freed 21722, aso having extremly low movement speed. mob_enslaved_netherwing_drake

## Quest: Zuluhed the Whacked
- [x] Zuluhed only has 4k hp (id(normal) = 11980, id(morphed) = 22330 ), this can't be right. - **FIXED IN https://github.com/cmangos/tbc-db/commit/e6623c09f6fb43d400586c0d443ddbc16fea70e0**
- [ ] The archers are standing in the air after aggroing:
![6](https://user-images.githubusercontent.com/9959527/32121903-c9e17518-bb5e-11e7-93f2-c55be99a70ad.jpg)
- [x] 22331 (Dragonmaw Elite) stationary?
- [x] portal joins combat due to missing flags and doesnt spawn demons as it only does that out of combat
- [ ] resettime of event around Zuluhed, adds dont respawn and he doesnt despawn it seems.

## Quest: Ally of the Netherwing (id = 10870 )
- [ ] When flying away on the dragon, the viewing angle is wrong and the model of the dragon looks strange. Also there seems to be flying a second dragon flying  alongside of the player. Please try yourself.
![7](https://user-images.githubusercontent.com/9959527/32122294-28d59378-bb60-11e7-9933-25da6955f7fb.jpg)

# NEUTRAL TO FRIENDLY

## Quest: Blood Oath of the Netherwing
- => all ok
## Quest: In Service of the Illidari
- 250 rep gained - ok
- => all ok
## Quest: Enter the Taskmaster
- => all ok
## Quest: Your Friend On The Inside
- => all ok
## Quest: A Job Unfinished...
- [x] The elites "Arvoar the Rapacious" (id = 23267 ) and "Barash the Den Mother" (id = 23269 ) have 7k hp but shoud have like 23K [arvoar](http://www.wowhead.com/npc=23267/arvoar-the-rapacious) [barash](http://www.wowhead.com/npc=23269/barash-the-den-mother#comments). They also should cast Fear and some kind of Shell but do not. (pls refer to the wowhead comments)  - **FIXED IN https://github.com/cmangos/tbc-db/commit/e6623c09f6fb43d400586c0d443ddbc16fea70e0**
- [x] Dragonmaw Ascendant (id = 22253 ) should be hostile while under fel orc disguise.
- gives 250 rep - ok
## Quest: The Great Netherwing Egg Hunt
- [ ] Did not check this yet, but [this video](https://www.youtube.com/watch?v=2rumkxSmhrQ) seems to show spawn locations but my impression is that there are plenty of eggs lying around.
- gives 350 rep - ok

## (Repeatable) Quest: Accepting All Eggs
- gives 250 rep - ok
- => all ok
## (Daily) Quest: Netherwing Crystals
- [ ] Dropchance from the Netherwing Rays seems (id = 23501 ) is 31% is that correct?
- gives 250 rep - ok

## (Daily) Quest: A Slow Death
- [ ] These gentlemen ( id= 23311 ) need to be hostile, even when disguised. Hey also should yell some stuff. (id= 23311 ) [src ](http://de.wowhead.com/npc=23311/ungehorsamer-peon-des-drachenmals#english-comments)(ctrl-f "are hostile") [src2](https://www.youtube.com/watch?v=KPtoaVkI7Bc&feature=youtu.be&t=229)
![9](https://user-images.githubusercontent.com/9959527/32137538-1eb8a3fe-bc22-11e7-990d-5e6eb1440e85.jpg)
- gives 250 rep - ok

## (Daily) Quest: The Not-So-Friendly_Skies...
- [ ] The creature ( id = 23188 ) which is supposed to be ambushed isnt spawned very often (5 on Dragonmaw Skyway and 1 on Dragonmaw Fortress) Most of them hang around on x = 76.0901 y = 80.5227, but they should patrol around the floating platforms. [src](https://www.youtube.com/watch?v=ClbhM_BVZHA)
`SELECT * FROM `creature` WHERE id = '23188'
- gives 250 rep - ok

## (Daily)(Skinning 300+) Quest: Nethermine Flayer Hide

- gives 250 rep - ok
- => all ok

## (Daily)(Herbalism 300+) Netherdust Pollen

- gives 250 rep - ok

## (Daily)(Mining 300+) Nethercite Ore

- [ ] like the herb nodes, not sure about the quantity of them, db says 24 wowhead = [src](http://www.wowhead.com/object=185877/nethercite-deposit)
`SELECT * FROM `gameobject` WHERE id = 185877`
- gives 250 rep - ok

# FRIENDLY TO HONORED

## Quest: Rise, Overseer!
- gives 250 rep - ok
- [ ] The item you get from the Quest [Overseer's Badge]
 (id= 32694 )(https://wow.gamepedia.com/Overseer%27s_Badge) didnt spawn the little dragon after I got it and the cooldown bugged (showed as ready but was on CD). After restarting my server and client I could spawn the mob just fine.
- [ ] The Netherwing Ally (id = 23320 ) should cast some spells but just auto attacks [src](http://www.wowhead.com/item=32694/overseers-badge#comments) "ctrl-f "casts"
- [ ] The Overseer's Badge should only be usable in Shadowmoon Valley, but I could use it in Searing Gorge,
## Quest: The Netherwing Mines
- gives 75 rep - ok
- => all ok
## (Daily) Quest: Picking Up The Pieces...
- gives 350 rep - ok
- => all ok
## (Daily) Quest: Dragons are the Least of Our Problems
- [ ] The quest givers (id = 23376 ) and their carts should wait when talked to. Instead they continue walking when you speak to them to accept the quest. [ref](https://www.youtube.com/watch?v=CObf9PKODkM)
- gives 350 rep - ok

## Quest: Crazed and Confused
- gives 350 rep - ok 
- => all ok

## Quest: The Great Murkblood Revolt
- [x] The quest item (id = 32724 )has a 2% chance to be in this https://wow.gamepedia.com/Sludge-Covered_Object and didnt drop. - **FIXED IN https://github.com/cmangos/tbc-db/pull/430**
- gives 350 rep - ok

## Quest: Seeker of Truth
- gives 500 rep - ok
- => all ok

## Quest: Overseeing and You: Making the Right Choices
- [x] Tyrantus should have 10k hp [src ](https://wow.gamepedia.com/Tyrantus)and use some abilities but doesnt. - **FIXED IN https://github.com/cmangos/tbc-db/pull/279**
- gives 250 rep - ok

## (Daily) Quest: The Booterang: A Cure For The Common Worthless Peon (id = 11055)
- [ ] It is possible to use the Booterang (id = 32680 ) on a Disobedient Peon multiple times, but you should only be used to use it once
- [ ] The peons should say some funny lines when being hit with the Booterang.  [src](http://www.wowhead.com/quest=11055/the-booterang-a-cure-for-the-common-worthless-peon#comments)
- [ ] After "booting" 11 peons I could not progress the quest and the command ".quest complete 11055" didnt work.. the error persisted after restarting the server. Something is busted.

- gives 350 rep -ok

**Comment by berserkingyadis** [comment]
Ill continue my text here.

# HONORED TO REVERED
## Quest: Stand Tall, Captain!

**Comment by berserkingyadis** [comment]
# Revered to Exalted
## Quest: Hail, Commander

**Comment by berserkingyadis** [comment]
# EXALTED
## Quest: Bow to the Highlord
- => all ok
## Quest: Lord Illidan Stormrage
1. Illidan is hostile and attacks on sight 
2. Dialogue goes thrugh just fine but Illidan does not disappear after it.
3. Normally the netherdragon takes you away but nothing happens.
4. When talking to Yarzill the Merc and selecting "Let's go!" there is an error message "You are too far away from the taxi stand"

5. This quest is not completeable.

**Comment by killerwife** [comment]
Quest: The Soul Cannon of Reth'hedron - likely the last elemental has a 256 UnitFlag flag UNIT_FLAG_IMMUNE_TO_PLAYER and its not being removed by the script.

**Comment by killerwife** [comment]
Sludge covered object, try setting chance to 100% and you will see if it drops or not.

**Comment by berserkingyadis** [comment]
I updated all relevant IDs and will start with trying to fix the Quest: The Great Murkblood Revolt

**Comment by berserkingyadis** [comment]
Maybe related, so I'll list this here. 
https://github.com/cmangos/tbc-db/commit/2b5c687386c62420473ce5b1a4d9c943ac3cd475
https://github.com/cmangos/tbc-db/commit/2f50be07990efcc5f064764c8dda78a33a10109e
https://github.com/cmangos/tbc-db/commit/a59526e7c6488cf61f152dcc651ae7afbd0423a8
https://github.com/cmangos/tbc-db/commit/aef1bbbaf3bec8667738d9c3130491ff0ad41170

Ill check if these commits changed something I observed

**Comment by AnonXS** [comment]
[ACID] Correct Spellid for c.22342 - https://github.com/cmangos/tbc-db/pull/426

**Comment by berserkingyadis** [comment]
https://github.com/cmangos/tbc-db/commit/2b5c687386c62420473ce5b1a4d9c943ac3cd475 added the Spell "Arcane Bolt" to the Netherwing Ally, but it does not cast it. The creature does not have any mana, could this be the issue?

**Comment by killerwife** [comment]
Absolutely, Netherwing ally should have mana. Post the creature IDs and I will try to look them up.

**Comment by killerwife** [comment]
Race quests - single SD2 script, each own Waypoints and fail quest if too far from creature. Will try to supply waypoints, to some if not all.
The Deadliest Trap Ever Laid - aldor and scryer are exclusive on each day, likely one SD2 script for them, and just interpolate targets/positions.
The Overseer's Badge should only be usable in Shadowmoon Valley, but I could use it in Searing Gorge, - missing spell_template AreaId, unless its usable in more zones, then it should be in spell_area
The Soul Cannon of Reth'hedron - unremoved 256 flag likely at the end of script due to relations changes.

All hp and damage issues will be fixed globally for whole DB.

**Comment by berserkingyadis** [comment]
@killerwife Entry of the Netherwing Ally is 23320

Ingame it has no mana but creature_table says it does
![screenshot_2017-11-07_15-08-36](https://user-images.githubusercontent.com/9959527/32497651-84075b44-c3cd-11e7-83dd-54b640b88465.png)

**Comment by berserkingyadis** [comment]
Considering the big commit today I checked the HP values of the creatures and everything looks good!

The Dragonmaw Ascendant Elites ( 22253 ) still hit too hard i think.. got 7k damage on a full t6 prot pala.
![screenshot_2017-11-08_00-20-28](https://user-images.githubusercontent.com/9959527/32523385-5879f272-c41b-11e7-90b4-c8b98a647c98.png)

This was changed in the CLS export:
`UPDATE creature_template SET MinLevel=72,MaxLevel=72,UnitClass=1,Expansion=1,HealthMultiplier=15,PowerMultiplier=1,DamageMultiplier=8 WHERE entry=22253;
`

**Comment by berserkingyadis** [comment]
Quest: Dragons are the Least of Our Problems:
The questgiver Neltharaku (entry: 21657, guid: 75654) stops flying when talked to , maybe useful for the q giver who keeps walking

**Comment by Saltgurka** [comment]
```
This drake is flying while on the ground (GUID: 75828):
```
The issue here is that the creature InhabitType is 5 (Over Ground Always Flying). If I remember correctly, these creatures start out sleeping on the ground until they are freed, at which point they start flying.
The creatures currently have an SD2 script, but try changing the InhabitType in DB and see if it causes any issues with the script.

**Comment by berserkingyadis** [comment]
Currently working on the booterang on which I will be opening a WIP PR soon.

This is a good overview about the quest flow: https://wow.gamepedia.com/Netherwing

**Comment by BillytheOrc** [comment]
"{ Using the item "Enchanted Nethervine Crystal" (id = 31652 ) on the drakes should fire a projectile (like in https://youtu.be/negt5rQFBoQ?t=35) but it fires nothing" 
was fixed.

"Can use item 31652 repeatedly on already freed 21722, aso having extremly low movement speed. mob_enslaved_netherwing_drake"
can be fixed pretty easily, but you guys may not like my fixes :p

**Comment by berserkingyadis** [comment]
_can be fixed pretty easily, but you guys may not like my fixes_

if your fixes are accompanied by valid sources there is no subjectivity involved. they will be approved

**Comment by berserkingyadis** [comment]
Its been a while since this issue was opened and I'm not sure how up to date it is. 

Unless somebody knows the current state the quests should be re-checked if they have been fixed in the time past.

**Comment by killerwife** [comment]
Except reworking Zuluhed the Whacked quest, this is mostly done. Closing this in favor of future issue.
