### ISSUE TITLE
Class-level-stats collisions

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#465]
This is an outstanding list of collisions
https://gist.github.com/killerwife/8bffb1768f9f72e0d5d504b9f84aef74
Each needs to be explicitly checked against sniffs or other viable source of data.
Expansion is in QUERY_CREATURE_RESPONSE and UnitClass is in UNIT_FIELD_BYTES_0
I plan to do this when I can do it in an automated way, if someone chooses to do it manually, go ahead.
People concerned:
@Grz3s @cala @malcrom 

- [ ] Entry: 62; Name: Gug Fatcandle; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 89; Name: Infernal; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 128; Name: Angry Programmer Tweedle Dee; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 353; Name: Antonia Dart; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 583; Name: Defias Ambusher; Malcrom unitclass: 4; Voa Unitclass: 1
- [ ] Entry: 765; Name: Swampwalker Elder; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 882; Name: Bone Caster; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 928; Name: Lord Grayson Shadowbreaker; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 1055; Name: Dreamhunter; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 1574; Name: Mage 1; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 1575; Name: Mage 5; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 1764; Name: Greater Feral Spirit; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 1798; Name: Tortured Soul; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 1800; Name: Cold Wraith; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 1964; Name: Treant; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 2056; Name: Ravenclaw Apparition; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 2060; Name: Councilman Smithers; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 2160; Name: Gravelflint Geomancer; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 2624; Name: Gazban; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 2942; Name: Dylan Bissel; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 3582; Name: Aman; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 3698; Name: Bolyun; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 3770; Name: Bleakheart Shadowstalker; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 3843; Name: Anaya; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 3860; Name: Shadowfang Tainted One; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 4277; Name: Eye of Kilrogg; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 5520; Name: Spackle Thornberry; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 5980; Name: Broken One; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 5981; Name: Portal Seeker; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 6197; Name: Spitelash Sorceress; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 6214; Name: Irradiated Burrower; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 7074; Name: Judge Thelgram; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 7525; Name: World Leatherworking Dragonscale Trainer; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 7779; Name: Priestess Tyriona; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 8394; Name: Roland Geardabbler; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 8443; Name: Avatar of Hakkar; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 8856; Name: Tyrion's Spybot; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 10296; Name: Vaelan; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 10340; Name: Vaelastrasz the Red; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 10493; Name: Risen Sorcerer; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 10538; Name: Vaelastrasz; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 10813; Name: Balnazzar; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 10819; Name: Baron Bloodbane; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 11779; Name: Shadowshard Thunderer; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 12379; Name: Unliving Caretaker; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 12756; Name: Lady Onyxia; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 13419; Name: Ivus the Forest Lord; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 13539; Name: Champion Coldmine Surveyor; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 13557; Name: Champion Irondeep Surveyor; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 13916; Name: Dire Maul Crystal Totem; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14242; Name: [UNUSED] Sulhasa; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 14385; Name: Doomguard Minion; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14452; Name: Enslaved Doomguard Commander; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14512; Name: Corrupted Spirit; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 14514; Name: Banal Spirit; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 14519; Name: Aspect of Corruption; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 14530; Name: Solenor the Slayer; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14533; Name: Simone the Seductress; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14639; Name: Zapped Deep Strider; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14684; Name: Balzaphon; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14686; Name: Lady Falther'ess; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14690; Name: Revanchion; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14693; Name: Scorn; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 14694; Name: Necrosis; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14702; Name: Wailing Widow; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14703; Name: Death Siren; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14705; Name: Nerubian Webspinner; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 14987; Name: Powerful Healing Ward; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 15007; Name: Sir Malory Wheeler; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 15121; Name: Skeletal Magelord; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 15211; Name: Azure Templar; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 15328; Name: Darkmoon Steam Tonk; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 15438; Name: Greater Fire Elemental; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 15559; Name: Elder Highpeak; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 15639; Name: Arcane Warder; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 15640; Name: Arcane Enforcer; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 15720; Name: Timbermaw Ancestor; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 15847; Name: Might of Kalimdor Shaman; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 15855; Name: Tauren Rifleman; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 15856; Name: Tauren Primalist; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 15859; Name: Stormwind Archmage; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 15860; Name: Kaldorei Marksman; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 15868; Name: Highlord Leoric Von Zeldig; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 15869; Name: Malagav the Tactician; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16048; Name: Lord Valthalak Trigger; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 16143; Name: Shadow of Doom; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16365; Name: Master Craftsman Omarion; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16381; Name: Archmage Tarsis Kir-Moldir; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16387; Name: Atiesh; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 16438; Name: Skeletal Trooper; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16446; Name: Plagued Gargoyle; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16451; Name: Deathknight Vindicator; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16452; Name: Necro Knight Guardian; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 16478; Name: Lieutenant Orrin; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16494; Name: Lieutenant Rukag; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16684; Name: Zelanis; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16685; Name: Elara; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16686; Name: Nerisen; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16694; Name: Karen Wentworth; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 16696; Name: Krukk; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 16744; Name: Driaan; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 16859; Name: Dragonhawk Hatchling; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16861; Name: Death Lord; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16874; Name: Bleeding Hollow Shadowcaster; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 16969; Name: Bone Magus Warlor; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 17062; Name: Fel Orc Corpse; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 17389; Name: Shadowmoon Voidcaller; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 17396; Name: Shadowmoon Sorcerer; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 17416; Name: Orc Captive; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 17499; Name: Vision of the Forlorn; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 17508; Name: Galaen's Corpse; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 17524; Name: Nazzivus Summoner; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 17600; Name: Draenei Cartographer; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 17601; Name: Pack Elekk; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 17638; Name: Siltfin Ambusher; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 17640; Name: Bristlelimb Ambusher; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 17739; Name: Outland Chimera, White; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 17832; Name: Blood Knight Dawnstar; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 17873; Name: Murkblood Henchman; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 17903; Name: Skeleton Mage; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 18040; Name: Lich; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 18041; Name: Doomguard Lord; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 18254; Name: Shadow of Aran; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 18271; Name: Consortium Prospector; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 18403; Name: Sporebat; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 18496; Name: Dugar; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 18613; Name: Orc Captive (1); Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 18625; Name: Dark Portal Dummy; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 18674; Name: [UNUSED]Anchorite Lyteera; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 18726; Name: Flying Raging Soul; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 18774; Name: Tatiana; Malcrom unitclass: 2; Voa Unitclass: 8
- [ ] Entry: 18778; Name: Cosmetic Raging Soul; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 18838; Name: Nightlord Malphas; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19233; Name: Flying Voidwalker; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19268; Name: Bleeding Hollow Vizier; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19287; Name: Invading Voidwalker; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19288; Name: Dreadknight; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19290; Name: Invading Anguisher; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19403; Name: Goblin Steam Tonk; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 19404; Name: Gnomish Steam Tonk; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 19407; Name: Azuremyst Vindicator; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19464; Name: Bleeding Hollow Soul; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19477; Name: Fleeing Dreghood Warrior; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19566; Name: Nethergarde Advisor; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19567; Name: Watcher Theronus; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19774; Name: Toban; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 19777; Name: Elaando; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 19914; Name: Hutihu; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 19922; Name: Tornado; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 19972; Name: Night Walker; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 20002; Name: Hurlog Horde; Malcrom unitclass: 1; Voa Unitclass: 8
---
- [ ] Entry: 22003; ERROR 1690 (22003) at line 7: BIGINT UNSIGNED value is out of range in '(`mangos`.`creature_template`.`MaxLevelMana` - `mangos`.`creature_template`.`MinLevelMana`)'
---
- [ ] Entry: 20120; Name: Tolo; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 20122; Name: Bloodscale Sea Witch; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 20148; Name: Dead Doomguard; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 20157; Name: Fleeing Dreghood Geomancer; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 20274; Name: Keldor the Lost; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 20496; Name: Kirin'Var Spectre; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 20618; Name: Mana Invader; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 20735; Name: [UNUSED]Bloodseer Lan'dalock; Malcrom unitclass: 8; Voa Unitclass: 2
- [ ] Entry: 20790; Name: Malevus the Mad; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 21001; Name: Kaylaan the Fallen; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 21155; Name: Senior Sergeant Eveningshade; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 21165; Name: Dihyana the Huntress; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 21210; Name: Invis Deathforge Caster; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 21211; Name: Invis Deathforge Target; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 21276; Name: Kil'sorrow Agent; Malcrom unitclass: 1; Voa Unitclass: 2
---
- [x] Entry: [21448](https://github.com/cmangos/tbc-db/commit/6307a76348e3093bd8900eb09f5362f5de97272b); and all other town/city guardian npcs have corrupted data for tbc, get data from wotlk-db
---
- [ ] Entry: 21647; Name: Shadowmoon Sorcerer (1); Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 21685; Name: Oronok Torn-heart; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 21821; Name: Proto-Nether Drake; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 21862; Name: Dark Portal Dummy 1.30; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22005; Name: Tem; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 22064; Name: Stormspire Drake; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 22067; Name: Scryer Dragonhawk; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 22094; Name: Remnant of Hate; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22205; Name: Lord Corruptor; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 22251; Name: Dragonmaw Archer; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 22437; Name: Remnant of Malice; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22438; Name: Remnant of Greed; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22439; Name: Remnant of Corruption; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22440; Name: Remnant of Pride; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22448; Name: Rexxar; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22810; Name: Rescued Cenarion Expedition Druid; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 22815; Name: Rescued Keepers of Time Custodian; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 22826; Name: King Dorfbruiser; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22828; Name: Trelopades; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22840; Name: Ashtongue Illusion; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 22856; Name: Reliquary of the Lost; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 22917; Name: Illidan Stormrage; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 23025; Name: Rizzle's Depth Charge; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 23320; Name: Netherwing Ally; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23343; Name: Wrangled Aether Ray; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23390; Name: Bash'ir's Harbinger; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23391; Name: Bash'ir; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23393; Name: Deathshadow Agent; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23404; Name: Imp Retainer; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23406; Name: Jimmy McWeaksauce; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23443; Name: Dragonmaw Raid Credit Marker (Scryers); Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 23454; Name: Dragonmaw Raid Credit Marker (Aldor); Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 23474; Name: Shivan Assassin (Red); Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23475; Name: Shivan Assassin (Blue); Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23476; Name: Shivan Assassin (Black); Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23506; Name: Broken Illusion; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23565; Name: Turgore; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23682; Name: Headless Horseman; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 23686; Name: Headless Horseman Flame Bunny; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 23694; Name: Pulsing Pumpkin; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 23705; Name: Catlord Corpse; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 23716; Name: Hexxer Corpse; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 24222; Name: Windy Cloud; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 24410; Name: Vazruden the Herald Image; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 24411; Name: Shattered Hand Centurion Image; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 24420; Name: The Black Stalker Image; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 24433; Name: Pathaleon Image; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 24529; Name: Voodoo Servant; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 24782; Name: Weakened Morbent Fel; Malcrom unitclass: 1; Voa Unitclass: 8
- [ ] Entry: 24808; Name: Broken Sentinel; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 24855; Name: Kael'thas Sunstrider Image; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 24955; Name: Emaciated Felblood; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 24981; Name: Converted Sentry; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 24998; Name: Mariner Farsight; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 25007; Name: Mariner Evenmist; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 25022; Name: Mariner Stillwake; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 25023; Name: Mariner Everwatch; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 25053; Name: Mariner Farseeker; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 25056; Name: Mariner Stillglider; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 25546; Name: Broken Sentinel (1); Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 25588; Name: Hand of the Deceiver; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 25708; Name: Sinister Reflection; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 25949; Name: Ice Caller Briatha; Malcrom unitclass: 8; Voa Unitclass: 1
- [ ] Entry: 26579; Name: Anveena Replica; Malcrom unitclass: 2; Voa Unitclass: 1
- [ ] Entry: 26650; Name: Durnholde Captain; Malcrom unitclass: 1; Voa Unitclass: 2
- [ ] Entry: 26651; Name: Durnholde Captain (1); Malcrom unitclass: 1; Voa Unitclass: 2

**Comment by evil-at-wow** [comment]
Would WoTLK era sniffs do, or would you require TBC era sniffs?

**Comment by killerwife** [comment]
Unless its a guard, wotlk era will suffice. But for some, it won't be enough, because some on that list were removed at some point. Most didn't change even in legion. Its just time consuming to dig it up.

**Comment by AnonXS** [comment]
What are we going to do about corrupted Guard Data and i bet some other data update with sources?
e.g.: http://www.wowhead.com/npc=21448/gadgetzan-sniper
https://wow.gamepedia.com/index.php?title=Gadgetzan_Sniper&direction=next&oldid=1935939

https://raw.githubusercontent.com/cmangos/tbc-db/master/Updates/785_CLS_wave_2.sql

```
UPDATE creature_template SET MinLevel=27,MaxLevel=28,UnitClass=1,Expansion=0,HealthMultiplier=1.05,PowerMultiplier=1,DamageMultiplier=1 WHERE entry=21448;
```

**Comment by malcrom** [comment]
Why do I see my name so many times?

**Comment by malcrom** [comment]
When I did mine I did every creature wrath and below. I fixed many but can't confirm they are all correct.

**Comment by Levitanious** [comment]
Why they look like someone inverted imports? o_o

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/3bbc7d51a8b4079a0f65f9cff203a7a95f75c39d
