### ISSUE TITLE
Why there is no InstallFullDB.sh in TBC db repo?

### ISSUE THREAD

**Issue by gordonpro** [cmangos/tbc-db#5]
Classic and UDB are all have `InstallFullDB.sh` script for Linux platform.

**Comment by killerwife** [comment]
‎Because tbc-db is currently under construction. Cyberium will commit it soon to the repo. I have around 800 files I need to process before it is up to date and that will tak some time.

**Comment by killerwife** [comment]
Fixed in https://github.com/cmangos/tbc-db/commit/624e145712601f0e724e5e999c3a8c7772161c7e

**Comment by gordonpro** [comment]
It is well, I tested.
https://github.com/cmangos/issues/wiki/Installation-Instructions
Maybe, the document need to update.
