### ISSUE TITLE
Lots of (startup) errors again.

### ISSUE THREAD

**Issue by evil-at-wow** [cmangos/tbc-db#586]
I took the most recent code for a test run and noticed there are lots of (startup) errors again, so here's an overview of unique error I got in my logs from a first test run.
I don't think it makes much sense to log each of them separately because several errors are typically similar and are fixed in one batch anyway, although there are quite a few errors. My suggestion is that for now I just list them all and we reply with commits that fix things until quite a few are handled, at which point I can verify the fixes and **update** this issue with a new list of startup errors.

For reference, here's the test environment:
System: Linux 64-bit
Cmake Option: Core built without playerbot
Core: latest
Database: latest

---

**DBErrors**:

2019-06-19 16:36:51 Creature (Entry: 23473) has GossipMenuId = 8736 for nonexistent menu
2019-06-19 16:36:51 Table gossip_menu_option for menu 8228, id 0 has unknown option id 100. Option will not be used
2019-06-19 16:36:51 Table gossip_menu_option for menu 8228, id 1 has unknown option id 101. Option will not be used

---

**EventAIErrors**:

2019-06-19 16:36:52 Event 2346701 Action 3 uses nonexistent SpellID 39663.

---

** Ongoing Errors **:

DoCastSpellIfCan by Creature (Entry: 18986 Guid: 68262) attempt to cast spell 13903 but spell failed due to unknown result 11.

**Comment by Levitanious** [comment]
Count me in! Let the janitor wagon roll-roll-roll :>

**Comment by evil-at-wow** [comment]
@AnonXS It's very, very unfortunate that you kept doing in place edits in my initial post despite my explicit request to add comments instead. There are actually so many edits now that I can't even find my original post in all the edits any more! :angry: 

Looking at the timestamps in whatever is here now, it looks like you only list startup errors, but my list contained a lot more than just startup errors. There were also errors you (only) got when playing, like when you ran a specific dungeon, or did a quest. It's probably impossible to verify those now for me. Oh well...

**Comment by AnonXS** [comment]
The nonstartup errors are issues that should be reported 1 by 1 to https://github.com/cmangos/issues as they are real scripting issues or need to be silenced incase of false positives by core repos.

**Comment by cyberium** [comment]
>The nonstartup errors are issues that should be reported 1 by 1 to https://github.com/cmangos/issues as they are real scripting issues or need to be silenced incase of false positives by core repos.

@AnonXS even if its right its not a reason to delete datas in a another one issue especially when that one explicitly asked to not do it? Am i missing something?

**Comment by AnonXS** [comment]
He did not state so in the head of this issue.
If i had not updated this issue with current errors it would have been closed for irrelevance long ago.
`I just list them all and we reply with commits that fix things until quite a few are handled, at which point I can verify the fixes and update this issue with a new list of startup errors.`

**Comment by evil-at-wow** [comment]
Well, "reply" of course implies "adding a new comment" (rather than "editing in place"), and "I can update" strictly speaking implies me doing it. I think my original text mentioned something like we could also close this issue after a few were handled/verified and open a new issue instead with an updated/new list. But anyway, let's just drop the discussion here and forget the whole thing. It happened, we can't turn back time anyway, so let's move on :smile:

As for reporting non-startup issues as separate issues: fair enough, but that's not possible any more for the ones in this list (as I mentioned, I can't go back in the edit history far enough to see my initial text), so that'll be for future ones.

TIL: not everything on the internet stays on the internet forever! :grin:

**Comment by cyberium** [comment]
Your second answer is much more clear and appropriate than the one before.
Your workflow is yours. But next time at least keep the original post and use only ~that kind of markdown feature~ instead.

No one like to see their words transformed/removed. I just wanted to point that out so nothing more to say about this. Keep the good work up ;)
