### ISSUE TITLE
failure on db import

### ISSUE THREAD

**Issue by hlarsen** [cmangos/tbc-db#59]
the install script bails on the following error:

`
...
   process update Updates/SpinOnTop/223_saltgurka_lbrs_rework.sql
ERROR 1062 (23000) at line 35: Duplicate entry '84134' for key 'PRIMARY'
ERROR: cannot apply Updates/SpinOnTop/223_saltgurka_lbrs_rework.sql
`

**Comment by cavaclub** [comment]
same with me!

**Comment by MantisLord** [comment]
Thank you, we are aware of this issue and it will be addressed soon.
