### ISSUE TITLE
Phantom Valets do not have stealth detection

### ISSUE THREAD

**Issue by Saben65** [cmangos/tbc-db#6]
>Clearly they have stealth detection to prevent partygoers from sneaking in!
>
>Phantom Valet says: Hey! Where do you think you are going, sneaking around like that?
Phantom Valet hits you for 8580.
>
>In summary, do not try to pickpocket them, even while engaged.

http://www.wowhead.com/npc=16408/phantom-valet#comments:id=52802

Suggested fix
```SQL
-- Add stealth detection to Phantom Valets (Karazhan)
UPDATE `creature_template_addon` SET `auras`='18950' WHERE `entry`=16408;
```

**Comment by killerwife** [comment]
Closed in https://github.com/cmangos/tbc-db/commit/6ba206588a58d7fb021d7d27353d364f8b630297
