### ISSUE TITLE
q.9738 Error

### ISSUE THREAD

**Issue by keyshuwen** [cmangos/tbc-db#604]
Naturalist Bite Discovered fault.

I tried to fix it.

INSERT INTO `gossip_menu` VALUES (7520, 9119, 7520, 0);
INSERT INTO `dbscripts_on_gossip` VALUES (7520, 0, 8, 17893, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'killcredit');

I don't understand this very well.

https://github.com/cmangos/mangos-tbc/blob/33a99ec762c54dd110429ab0e94c54125d65b116/src/game/AI/ScriptDevAI/scripts/outland/coilfang_reservoir/slave_pens/instance_slave_pens.cpp#L76

I hope someone can help me. Thank you.

**Comment by killerwife** [comment]
DELETE FROM gossip_menu WHERE entry IN(7540,7520); -- NPC has two entries, has to be handled by SD2
INSERT INTO gossip_menu VALUES
('7520', '9119', '0', '0'),
('7540', '9144', '0', '0');
DELETE FROM gossip_menu_option WHERE menu_id IN(7540,7520);
INSERT INTO gossip_menu_option(menu_id, id, option_icon, option_text, option_id, npc_option_npcflag, action_menu_id, action_poi_id, action_script_id, box_coded, box_money, box_text, condition_id) VALUES
('7520', '0', '0', 'Alright, Bite, I\'ll let you out.', '1', '1', '0', '0', '7520', '0', '0', NULL, '0'),
('7540', '0', '0', 'Naturalist, please grant me your boon.', '1', '1', '-1', '0', '7540', '0', '0', NULL, '0');

DELETE FROM dbscripts_on_gossip WHERE id IN(7540,7520);
INSERT INTO `dbscripts_on_gossip` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES
('7520', '0', '8', '17893', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Naturalist Bite - Give Kill Credit to Group'),
('7520', '0', '13', '0', '0', '0', '182094', '5', '1', '0', '0', '0', '0', '0', '0', '0', '0', 'Naturalist Bite - Open cage'),
('7520', '0', '5', '46', '256', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Naturalist Bite - Remove Unit Flag IMMUNE_TO_PLAYER'),
('7520', '0', '5', '46', '512', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Naturalist Bite - Remove Unit Flag IMMUNE_TO_NPC'),
('7520', '0', '22', '113', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Naturalist Bite - Change faction'),
('7520', '0', '29', '1', '2', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Naturalist Bite - Remove NPC Gossip flag'),
('7520', '0', '20', '2', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Naturalist Bite - Move Waypoint'),
('7520', '0', '10', '17957', '300000', '1', '0', '0', '8', '1', '0', '0', '0', '-97.29962', '-744.0187', '34.83808', '3.476041', 'Naturalist Bite - Spawn Coilfang Champion'),
('7520', '0', '10', '17960', '300000', '1', '0', '0', '8', '1', '0', '0', '0', '-93.89555', '-741.5464', '35.76108', '3.737259', 'Naturalist Bite - Spawn Coilfang Soothsayer'),
('7520', '0', '10', '17961', '300000', '1', '0', '0', '8', '1', '0', '0', '0', '-90.23283', '-740.959', '35.3191', '35.94978', 'Naturalist Bite - Spawn Coilfang Enchantress'),
('7540', '0', '15', '34906', '3', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Naturalist Bite - Cast Mark of Bite');

DELETE FROM `dbscript_string` WHERE `entry` IN (2000001313,2000001314);
INSERT INTO `dbscript_string` (`entry`, `content_default`, `sound`, `type`, `language`, `emote`, `comment`) VALUES
(2000001313,'Uh oh!  It would appear that all of the noise you''ve been making has attracted some unwanted attention!', '0', '0', '0', '0', 'Naturalist Bite on Waypoint 2'),
(2000001314,'Intrudersss with the prisssoner!  Kill them!!!','0','1','0','0','Coilfang Champion on Releasing Naturalist Bite');

This is the fix. It will be in a week in tbc-db.

**Comment by keyshuwen** [comment]
Thanks...
