### ISSUE TITLE
what():  bind: Cannot assign requested address Aborted

### ISSUE THREAD

**Issue by zhidadiyu** [cmangos/tbc-db#606]
mangos>terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Cannot assign requested address
Aborted

**Comment by AnonXS** [comment]
This is the Database Issue Tracker, please refer these for further guidance.

https://github.com/cmangos/issues/wiki/Installation-Instructions
https://github.com/cmangos/mangos-tbc
https://github.com/cmangos/issues
