### ISSUE TITLE
SQL Update did not work

### ISSUE THREAD

**Issue by dagochen** [cmangos/tbc-db#618]
1 queries executed, 0 success, 1 errors, 0 warnings

Query: ALTER TABLE quest_template MODIFY RewMaxRepValue1 mediumint(9) NOT NULL DEFAULT '42999', MODIFY RewMaxRepValue2 mediumint(9) NOT...

Error Code: 1054
Unknown column 'RewMaxRepValue1' in 'quest_template'

in s2374_01_mangos_quest_template_rewmaxrep.sql

**Comment by Saltgurka** [comment]
MySQL version?

**Comment by dagochen** [comment]
5.7

**Comment by Saltgurka** [comment]
Some users have experienced issues when using MySQL versions above 5.6. 
Make sure both your db repo and your core repo is updated and paths correctly configured in the install script configuration. Try to completely drop and recreate your mangos_tbc database and rerun the install script. If it still does not work try to downgrande to MySQL 5.6.
