### ISSUE TITLE
DB 1.7 "a new hope" error on loading Server 

### ISSUE THREAD

**Issue by Cyneo7** [cmangos/tbc-db#619]
Hello,

I have a problem loading server TBC 2.4.3 mangos with the new database 1.7 "a new hope".

the server doesn't stop loading the "Creature" table

this appear all the time without stopping :

Loading Pet Create Spells...

>> Loaded 8 pet create spells from table and 474 from DBC
Loading Creature Data...
Table `creature` have creature (GUID: 6732 Entry: 721) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=1.
Table `creature` have creature (GUID: 6731 Entry: 440) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=449.
Table `creature` have creature (GUID: 6730 Entry: 485) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=605.
Table `creature` have creature (GUID: 6729 Entry: 485) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=605.
Table `creature` have creature (GUID: 6728 Entry: 485) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=605.
Table `creature` have creature (GUID: 15287 Entry: 2388) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=1900.
Table `creature` have creature (GUID: 11 Entry: 1215) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=1000.
Table `creature` have creature (GUID: 12 Entry: 1218) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=300.
Table `creature` have creature (GUID: 13 Entry: 12785) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=5700.
Table `creature` have creature (GUID: 14 Entry: 12777) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=8075.
Table `creature` have creature (GUID: 15 Entry: 12781) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=7700.
Table `creature` have creature (GUID: 16 Entry: 12778) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=2900.
Table `creature` have creature (GUID: 17 Entry: 12786) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=3500.
Table `creature` have creature (GUID: 18 Entry: 23446) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=8075.
Table `creature` have creature (GUID: 5500112 Entry: 20044) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (1), `creature_template`.`MinLevelHealth`=26000.
Table `creature` have creature (GUID: 5500112 Entry: 20044) with `creature_template`.`RegenerateStats` & REGEN_FLAG_POWER and low current mana (0), `creature_template`.`MinLevelMana`=31550.
Table `creature` have creature (GUID: 20 Entry: 12787) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=3300.
Table `creature` have creature (GUID: 21 Entry: 12784) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=5300.
Table `creature` have creature (GUID: 22 Entry: 12783) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=3600.
Table `creature` have creature (GUID: 23 Entry: 12782) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=8075.
Table `creature` have creature (GUID: 24 Entry: 19848) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=4000.
Table `creature` have creature (GUID: 25 Entry: 12780) with `creature_template`.`RegenerateStats` & REGEN_FLAG_HEALTH and low current health (0), `creature_template`.`MinLevelHealth`=3300.
........................

And more and more and never stop to let the mangos console be ready

Thanks in advance

**Comment by dunjeon** [comment]
I can't confirm. The update works for me.

**Comment by Cyneo7** [comment]
i did it, twice.
i drop the "mangos" database (world) and installed all from the begining, as say the guide (https://gist.github.com/Muehe/175d2e761169327d50c40eda2b6d4a32#location)

but always get that error

any idea for to solve it?

**Comment by Saltgurka** [comment]
Your core is out of date. Pull latest commit and rebuild to resolve the issue,
