### ISSUE TITLE
No Witnesses of Doom 22282 in BEM

### ISSUE THREAD

**Issue by Tobschinski** [cmangos/tbc-db#631]
there should be 3 in Forge Camp Wrath

**Comment by AnonXS** [comment]
thinking about it, as fleeing movegen does not make the npcs run towards other npcs anymore, we need to fixup their ais with the option to make fleeing capable to still do targeted fleeing, not random movement fleeing. @killerwife 

---

https://www.wowhead.com/npc=22282/witness-of-doom#comments:id=55165

```
Only thing these do as i´ve seen so far is that if you are spotted by one, it says "You are spotted by the Witness of Doom" and then the eye goes away and picks up closest mob that comes after you. They itself dissapear when it has "warned" the mob about you.
```

---

Same with Shadowmoon Eye of Kilrogg 22134

https://www.wowhead.com/npc=22134/shadowmoon-eye-of-kilrogg#comments:id=161783

```
While these mobs will not attack you directly, their only goal seems to be to patrol the entire Ata'mal Terrace. If they spot you, they will not attack you but instead will turn to the nearest hostile mob which is not yet engaged with you. When they reach the mob, the eye will despawn and the mob will try to engage you in combat. 
```
