### ISSUE TITLE
Gordunni Back-Breaker

### ISSUE THREAD

**Issue by Stitchedeye** [cmangos/tbc-db#638]
NPC Gordunni Back-Breaker (22143) above Shattrath gives an enrage buff to the attacker.

![wowscrnshot_021419_130949](https://user-images.githubusercontent.com/47632093/52786501-4a680900-305b-11e9-886b-b5df8126425d.jpg)

**Comment by AnonXS** [comment]
no issue: https://www.wowhead.com/spell=37974/enraging-strike
