### ISSUE TITLE
Mount X water collision

### ISSUE THREAD

**Issue by Stitchedeye** [cmangos/tbc-db#639]
Entering even the shallowest kind of water in open world will dismount you.
Also, mounts cannot be used while standing in water.
![wowscrnshot_021419_133329](https://user-images.githubusercontent.com/47632093/52787141-36bda200-305d-11e9-8ea3-e2aa00f3b608.jpg)

**Comment by AnonXS** [comment]
Core Issue: https://github.com/cmangos/issues/issues/1874
