### ISSUE TITLE
Missing pooling for q.299 spawns

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#666]
OBJECT_FIELD_ENTRY: 331
Stationary Position: X: -3425.584, -1758.089, 28.02624, -2.111848 -- have
GAMEOBJECT_ROTATION: X: 0, 0, -0.8703556 W: 0.4924237

Stationary Position: X: -3525.93, -1884.599, 24.24283, -0.5759573
GAMEOBJECT_ROTATION: X: 0, 0, -0.2840147 W: 0.9588199
OBJECT_FIELD_ENTRY: 333

Stationary Position: X: -3461.633, -1803.475, 25.70607, -1.832595
GAMEOBJECT_ROTATION: X: 0, 0, -0.7933531 W: 0.6087617
Stationary Position: X: -3469.871, -1836.429, 17.28823, 0
OBJECT_FIELD_ENTRY: 334

Stationary Position: X: -3525.93, -1884.599, 24.24283, -0.5759573
GAMEOBJECT_ROTATION: X: 0, 0, -0.2840147 W: 0.9588199

Stationary Position: X: -3568.4, -1845.557, 24.36173, -2.967041
GAMEOBJECT_ROTATION: X: 0, 0, -0.9961939 W: 0.08716504
OBJECT_FIELD_ENTRY: 35252

Stationary Position: X: -3549.775, -1723.89, 81.99398, 2.757613 -- have
GAMEOBJECT_ROTATION: X: 0, 0, 0.9816265 W: 0.1908124

Stationary Position: X: -3522.117, -1799.959, 23.93794, -1.815142 -- have
GAMEOBJECT_ROTATION: X: 0, 0, -0.7880106 W: 0.6156617

**Comment by killerwife** [comment]
All objects for this quest are pooled: https://classic.wowhead.com/quest=299/uncovering-the-past always one spawned of each

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/a5869e8bc768f6edd016aa02781c525e8651f093
