### ISSUE TITLE
Gobject 1727 - Keg of Shindigger Stout missing spawns + pooling

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#667]
Meant to have pooled a numerous spawns

**Comment by Tobschinski** [comment]
https://github.com/cmangos/classic-db/commit/629d381a6cdede0d076a45ad0fb69215adf64a30

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/9d93d0fa3cb809b8f2600fe04dfb23121caf8354
