### ISSUE TITLE
Quest Suspicious Hoofprints 1268 - missing afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#669]
Missing spawning of an NPC which runs by, talks, and runs off. Possibly data is in cata+ folder.

**Comment by Grz3s** [comment]
WotllDB has this already added

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/83f30b86382e739af2ef40ce91a69a938721d6f7
