### ISSUE TITLE
Ghostly Stewards are not immune to taunt.

### ISSUE THREAD

**Issue by Saben65** [cmangos/tbc-db#7]
>Ghostly Stwerds come in pairs and **are not tauntable**. So dps and healing should wait for some threat to be built. Focus fire on one steward. At 50% they enrage and hit for 3k to 4k damage (against about 12.5k armor). They can and should be disarmed when they enrage which will cut their dps in half.

http://www.wowhead.com/npc=16414/ghostly-steward#comments:id=41030

Suggested Fix
```SQL
-- Add taunt immunity to Ghostly Stewards (Karazhan)
UPDATE `creature_template` SET `extraflags`='256' WHERE `entry`=16414;
```

ExtraFlags are currently set to 0 for them.

**Comment by killerwife** [comment]
Closed in https://github.com/cmangos/tbc-db/commit/6ba206588a58d7fb021d7d27353d364f8b630297
