### ISSUE TITLE
Quest The Secret Compromised 10944 - afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#701]

**Comment by dr-j** [comment]
If this helps I actually scripted this a while ago on another project https://github.com/TrinityCore/TrinityCore/commit/ca73634e44f87bb76ad7cd9aaca0a8a0b11ee621 which was follow up to https://github.com/TrinityCore/TrinityCore/commit/d91fd684b5c5929c77b3f1cba260d6b8c3f58068

**Comment by killerwife** [comment]
Is it based on a sniff?

**Comment by dr-j** [comment]
yes of course it is I rarely commit anything which is not

**Comment by killerwife** [comment]
Thanks for the memo then. We will try to adapt it when there is time.

**Comment by Saltgurka** [comment]
https://github.com/cmangos/tbc-db/commit/322ce255fdf7060fdaa481b9ac506fca10f4cc25
