### ISSUE TITLE
Quest Find the Gems and Power Source 2339 - missing afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#706]

**Comment by miraco** [comment]
Do we have sniffs for this and the follow up quests? started working on this quest chain, but cant finish it my self on retail (would need 2 other ppl to summon endboss in uldaman)

**Comment by killerwife** [comment]
Should be in the package i gave you.

**Comment by miraco** [comment]
Okay, is there a list with what quest is in wich file? cause all "logical" files i searched for this quest didnt had it

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/commit/50e20532e4ebb80e88f513c437303abaee4e0ffe
