### ISSUE TITLE
[Engineering] item 4392 does not despawn/behaves as if pet

### ISSUE THREAD

**Issue by Comet701** [cmangos/tbc-db#718]
Have an Advanced Target Dummy on a char with engineering. Decided to drop it. Now it's following me around like a pet, and never despawns. Supposed to be stationary, and despawn after 15 secs.

Source:
https://wowwiki.fandom.com/wiki/Advanced_Target_Dummy
https://tbc-twinhead.twinstar.cz/?item=4392

---

https://github.com/cmangos/mangos-tbc/blame/master/sql/base/dbc/cmangos_fixes/Spell.sql#L1999

[SD] Add Script for npc_advanced_target_dummy 2674 so it can be looted by player

**Comment by killerwife** [comment]
Resolved already with spell_effect_summon_no_follow_movement
