### ISSUE TITLE
[BUG] all TBC Dungeons Bosses and Trash Loot missed 

### ISSUE THREAD

**Issue by cooler-SAI** [cmangos/tbc-db#72]
Hey all here! I am using Last TBC DB https://github.com/cmangos/tbc-db/commit/2f743478956a34417e7ad28a6d0d09e1e32bd27d with all updates. and Have a problem - all TBC Dungeons doesn't drop Blue, Green Items, Bosses Have only money Drop. Don't have this problem in TBC Raids.
Thanks anyway, hope this can be fixed

**Comment by Adeer** [comment]
world drops are also missing? Do not drop any green, blue, etc. Items.

**Comment by JapanLady42** [comment]
Bump

**Comment by Saben65** [comment]
@killerwife Does the loot system/tables from vengeance still need to be ported over?

**Comment by MantisLord** [comment]
Partial fix with https://github.com/cmangos/tbc-db/commit/7814660c18bc20f52b4b66a4dfe2b6ad44f59566

Still more to come.

**Comment by cooler-SAI** [comment]
good to see it ;)

**Comment by rayonpt** [comment]
Still missing loot in instances

**Comment by AnonXS** [comment]
reference_loot_template implemented in https://github.com/cmangos/tbc-db/commit/7814660c18bc20f52b4b66a4dfe2b6ad44f59566 are not connected to any creature_loot_template and therefore popping dberrors.

**Comment by keyshuwen** [comment]
#603  fix Raid loot 

It may need to be improved.  @AnonXS

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/2a71ca0b5a22f5b0cc64ef3851f3ea5eb14f7cbd should be the biggest part and one update for dungeon endbosses is also pending for export. hope everything is in place then.

**Comment by Saltgurka** [comment]
Solved with https://github.com/cmangos/tbc-db/commit/106915097925b9527069bd659dd340cdfc9b3d76 and https://github.com/cmangos/tbc-db/commit/81d09e93da3f2a7dab22282e6b4cb4b17a168a82
