### ISSUE TITLE
Fire Nova Totem for Shamans

### ISSUE THREAD

**Issue by Hotdogstand420** [cmangos/tbc-db#722]
Fire Nova Totem is supposed to last 4 seconds and let out an AOE explosion, but whenever i put my totem down it disappears after 1 second on it's own.

**Comment by killerwife** [comment]
Every second the totem does a threat pulse and 90% of the time mobs kill it immediately.

**Comment by Hotdogstand420** [comment]
but it disappears when no one is around, i can be in the open and it
vanishes

**Comment by killerwife** [comment]
Reproduced.

**Comment by tangko5290** [comment]
In the Blood Furnace dungeon boss - keli'dan the breaker (creatireid: 17377), he will cast the Fire Nova skill immediately after pulling away the skills of the surrounding players, causing crushing damage. Here, he should also release the Fire Nova by counting the seconds

**Comment by killerwife** [comment]
Should be resolved now.
