### ISSUE TITLE
Small Thorium Veins are raining Arcane Crystal in Ungoro

### ISSUE THREAD

**Issue by PulpDream** [cmangos/tbc-db#731]
Small Thorium Veins are raining Arcane Crystals in Ungoro

**Comment by AnonXS** [comment]
```
9597	12363	2,6	0	1	1	0	Arcane Crystal
13960	12363	2,6	0	1	1	0	Arcane Crystal
```

**Comment by AnonXS** [comment]
Interesting for classic-db though, as in classic only rich thorium veins hold arcane crystals. @cala

**Comment by cala** [comment]
I'll look at that. But I don't remember seeing this issue in Classic either. Thanks.
