### ISSUE TITLE
Redoubt Cloak sound

### ISSUE THREAD

**Issue by LightsVGH** [cmangos/tbc-db#732]
Redoubt Cloak doesn't make a sound when moved in inventory.

**Comment by LightsVGH** [comment]
Same thing with Duskbat Drape. Maybe more cloaks as well.

**Comment by LightsVGH** [comment]
Also true for Pumpkin Bag and Hourglass Sand.

**Comment by killerwife** [comment]
These are clientside, nothing to do with that.
