### ISSUE TITLE
Curse of Shadow, wrong spellbook tab

### ISSUE THREAD

**Issue by LightsVGH** [cmangos/tbc-db#733]
Curse of Shadow (warlock) is listed in the Spellbook under the General tab.

**Comment by MantisLord** [comment]
"Curse of Shadow" was removed as a spell in TBC, so it's actually showing in the correct tab.

https://wowwiki.fandom.com/wiki/Curse_of_Shadow
`Patch 2.4.3 (2008-07-15): This spell has been removed. Its function has been replaced by Curse of the Elements.`

Curse of Elements shows in the Affliction tab of the spell book correctly.
