### ISSUE TITLE
Scarlet Monastery emotes

### ISSUE THREAD

**Issue by LightsVGH** [cmangos/tbc-db#734]
Mobs in Scarlet Monastery use various incorrect emotes in combat, that I believe are lifted from looting tablets in Burning Steppes during the quest "The Smoldering Ruins of Thaurissan".

**Comment by evil-at-wow** [comment]
That sounds a lot as something cmangos/tbc-db@5d870ac355 fixes.

**Comment by MantisLord** [comment]
That's right - should be all fixed now.
