### ISSUE TITLE
Voidwalker's "Consume Shadow" channeling. [Warlock]

### ISSUE THREAD

**Issue by Neophrone** [cmangos/tbc-db#736]
Every time I try to use Consume Shadow channeling spell VW interupts himself. Probably becouse he stays on "Follow" command. Works properly only when I manually command him to "Stay" and use Consume Shadow after it.
However it should work with any command, he simply should stop and channel his spell until I command him to do another job or until the end of channeling.

**Comment by MantisLord** [comment]
Valid. This will be fixed in an upcoming core export.

**Comment by killerwife** [comment]
Resolved now.
