### ISSUE TITLE
Blacksmithing Booty Bay

### ISSUE THREAD

**Issue by Peaceout1983** [cmangos/tbc-db#739]
Brikk Keencraft <master blacksmith> in booty is missing most of the recipes from skill level 230 and upwards.
Only reason i found this was because of the Armorsmithing quest line.

**Comment by MantisLord** [comment]
The issue doesn't exist in tbc-db, Brikk already has all the proper recipes.

However I have a hunch why this was reported... this is a problem in a certain other database which is alot like tbc-db. The issue has been fixed there instead.
