### ISSUE TITLE
Quest The Attack!

### ISSUE THREAD

**Issue by Icesythe7** [cmangos/tbc-db#74]
this was fixed by xsavior(spelling?) while it was implemented almost 100% perfectly for some reason Marzon the Silent Blade is not flagged to attack-able when  Lord Gregor Lescovar is, thus the quest is not able to be complete as you can't kill the mob. I can see in the file that he is changed to faction 7 just like lord gregor but still isnt attackable for some odd reason.

**Comment by Grz3s** [comment]
```quote
this was fixed by xsavior
```
It wasn't ... 
Quest was Scripted by me... and backported by @killerwife in 069_Large_Old_UDB_Backport_Pack.sql
And i see that only text ID's were changed during that proces.
...
I dont have TBC client.. but in WoTLK.. same script works perfectly well..
Only diference i see:
creature 1755 "Marzon the Silent Blade" has NpcFlags = 2 (should have 0) .. 
creature 1755 "Marzon the Silent Blade" has faction = 84 .. (wotlk have 12) .. 
Chnge both ... it may fix your issue.
