### ISSUE TITLE
Rogue stealth talent "Master of Deception" is not working

### ISSUE THREAD

**Issue by worugru** [cmangos/tbc-db#740]
The  talent of rogue, named "Master of Deception" in the first row of Subtlety talent tree, is not working.

It is meant to make the rogue harder to detect, when talented. 

We have tried several times dueling with 2 rogues, one had the talent one didnt. And we both checked how far we could see each other, moving a bit by bit. The distance both rogues could see each other at stealth was same. Meaning talent was doing absolutely nothing.

PS : both rogues had no active ability, gear or racial ability to effect passive detention rates, like Night elf racial or activated human racial.

**Comment by killerwife** [comment]
Stealth level got reworked since then. Closing.
