### ISSUE TITLE
Blind consumes arrows

### ISSUE THREAD

**Issue by LightsVGH** [cmangos/tbc-db#742]
The rogue ability "Blind" consumes 1 arrow upon use, if you have any in your inventory.
It does not appear to be the same with bullets.
Tested with multiple variations of arrows, and with one type of bullets.

The ability does however still work if you don't have any arrows.

**Comment by Yatzii93** [comment]
LOL no way....I'm going to have to test this.

**Comment by Yatzii93** [comment]
Ye not happening my end.

**Comment by MantisLord** [comment]
Cannot reproduce.
