### ISSUE TITLE
26 creature_ai_text records which have no corresponding broadcast_text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#743]
entry | content_default | comment
-- | -- | --
-321 | Iman m t'ief fu Fus'obeah italaf | Common Frostmane Troll Text
-374 | [Dwarvish] Dum mos | 2149
-376 | [Orcish] Ogg kaz ko zugas kil mog Tov'nokaz Kagg | Orc Common Text
-377 | [Orcish] Tago mog regas gi mog Tov'nokaz Kagg | Orc Common Text
-388 | Hearty Kill! | 4831
-548 | Arrrhhh...Guards! | Common Horde Flight Master
-567 | Sleep... | 4832
-817 | So or'manley fi siame Dim fus siame yudo | 8580
-853 | Vanquish the weak! | Varimathras 2425
-854 | Time to die! | Varimathras 2425
-855 | None can oppose me. | Varimathras 2425
-1020 | Step right up! Step right up! Greetings my friend. I'm Silas Darkmoon and I want to welcome you to the greatest show on Azeroth! It's the Darkmoon Faire friend, and it's your lucky day! Sparing no expense, we've gathered wonders and treats from around th... | 14823
-1021 | Amaze at the wonders that the Darkmoon Faire has uncovered in this vast and mysterious world! We have spared no expense in bringing you excitement that children of all ages will delight in! | 14823
-1022 | We have it all... delicious food, strong drink, exotic artifacts, fortunes read, amazing prizes and excitement without end! | 14823
-1023 | And, don't forget to turn in your Darkmoon Faire Prize Tickets! All it takes is five or more and you're on your way to the most wondrous prizes on all of Azeroth. Everybody is a winner! | 14823
-1048 | You are in the presence of a god! | 15963
-1559 | Foolish mortals you do not yet see the potential of that Artifact. | 8506
-1561 | I sense my grip on the Dream twisting into chaos. | 8506
-10188 | Lok'tar Illidari! | Common Hellfire Orc Text
-10196 | My pets are hungry and they will dine on your flesh! | 17455
-10836 | The comedian impersonates a female tauren. | 19228
-10850 | The comedian impersonates a female dwarf. | 19228
-10851 | So this gnome tells a tauren he's been to Molten Core. | 19228
-10857 | I love night elf women. Especially when they say stuff like this... | 19228
-10858 | The comedian impersonates a night elf. | 19228
-10859 | The comedian impersonates an undead. | 19228

**Comment by MantisLord** [comment]
Fixed in https://github.com/cmangos/tbc-db/commit/7e8f03f753e242fd408597abf490623e73424579
