### ISSUE TITLE
[Fix] Timber Worg Alpha - spawned under texture

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#744]
`UPDATE` `tbcmangos`.`creature` SET `position_z` = '-43.0963' WHERE (`guid` = `'66527');`

This should do it. I found it accidentaly it is spawned under the map

**Comment by al3xc1985** [comment]
@killerwife can you check and push it please?

**Comment by AnonXS** [comment]
will be fixed in a later update
