### ISSUE TITLE
[The vengeful harbinger] "lava" spots and ultra fast respawns

### ISSUE THREAD

**Issue by babno** [cmangos/tbc-db#745]
In the room the tomb of lights for the above quest, many spots appear to be classified as lava and you will intermittently take ~500 fire damage with no source. Paladins take damage even when Divine Shield is active. It will appear in the combat log simply as "*Player name* suffers 472 fire damage."

In addition to this, mobs in the room respawn in roughly 15 seconds. I'm guessing this is a result of the increased spawn rates that have been implemented since launch, but it seems excessive here.

**Comment by AnonXS** [comment]
i think these are invisible fire gobjects, not lava

**Comment by MantisLord** [comment]
Should have been fixed awhile back.
