### ISSUE TITLE
[Mana Tombs] [Ethereal Darkcaster] Mana burn doing 4x damage

### ISSUE THREAD

**Issue by babno** [cmangos/tbc-db#747]
https://imgur.com/a/Rmi03p0

https://tbc-twinhead.twinstar.cz/icqllhtdorquzuml.html?npc=18331#abilities

As you can see they're doing damage equal to double the mana drained, when it should be half.

**Comment by killerwife** [comment]
Wrong place to report and fixed.

**Comment by babno** [comment]
May I ask where I should have reported this for future reference @killerwife

**Comment by killerwife** [comment]
https://gitlab.com/lights-vengeance/issues
