### ISSUE TITLE
[Paladin] [Righteous Defense] has no effect when used on pets/npcs

### ISSUE THREAD

**Issue by babno** [cmangos/tbc-db#748]
If you try to use it on a pet or friendly npc (such as an escort quest) it will consume the mana and put the ability on cooldown but not have any effect.

**Comment by babno** [comment]
@killerwife did you test it on NPCs? I know it now works on pets, but as of last Thursday I believe I still couldn't taunt off NPCs in MH.

**Comment by killerwife** [comment]
I changed it when I closed it. Pending deployment.
