### ISSUE TITLE
[Patch] Small script target for carverns of time

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#753]
DELETE FROM `spell_script_target` WHERE `entry` = 25158;
INSERT INTO `spell_script_target` VALUES (25158, 1, 15381);\

Credits HG

**Comment by AnonXS** [comment]
https://www.wowhead.com/npc=15381/anachronos-the-ancient#comments
`25158 Name: Time Stop` rp event probably

**Comment by al3xc1985** [comment]
Yes

**Comment by MantisLord** [comment]
We currently have a variety of different targets for this spell involved with a script in the area.
![image](https://user-images.githubusercontent.com/16798471/100054450-0ee19d80-2df0-11eb-9d87-895beef61e7b.png)

Do you recall what this is fixing?

**Comment by al3xc1985** [comment]
I don't remember at all... I might search again when I will have time...now I am in exams..
Beside that my computer with all the info is gone

**Comment by AnonXS** [comment]
https://tbc.wowhead.com/npc=15192/anachronos
https://tbc.wowhead.com/npc=15381/anachronos-the-ancient

not enough info to use this.
