### ISSUE TITLE
[Patch] Add binding heal 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#754]
`UPDATE spell_affect SET SpellFamilyMask=17179871232 WHERE entry=33158 AND effectId=1;
UPDATE spell_affect SET SpellFamilyMask=17179871232 WHERE entry=33159 AND effectId=1;
UPDATE spell_affect SET SpellFamilyMask=17179871232 WHERE entry=33160 AND effectId=1;
UPDATE spell_affect SET SpellFamilyMask=17179871232 WHERE entry=33161 AND effectId=1;
UPDATE spell_affect SET SpellFamilyMask=17179871232 WHERE entry=33162 AND effectId=1;

Credits HG`

**Comment by AnonXS** [comment]
nice find thanks
