### ISSUE TITLE
[Patch] Some loot for SWP missing

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#756]
`-- Sunwell: Add Sun-Drenched Scale Chestguard pattern to trash loot
INSERT INTO `reference_loot_template` VALUES (34091, 35219, 0, 1, 1, 1, 7, 165, 1);

-- Show specific recipes only to crafters
UPDATE `reference_loot_template` SET `condition_id` = 7, `condition_value2` = 1 WHERE `entry` = 34091 AND `item` IN (35209, 35213, 35214);`

I just picked it up, and was 2 late to transform the condition part... left here for reference so we can export it

Credits HG

**Comment by AnonXS** [comment]
maybe try looking at our db sometimes its all there now

```
SELECT * FROM `reference_loot_template` WHERE `entry` BETWEEN 36201 AND 36201 ORDER BY entry,item;
```

**Comment by al3xc1985** [comment]
I did. Did not find any info

**Comment by al3xc1985** [comment]
That is why i posted it. I did not find info... I will check again tonight

**Comment by al3xc1985** [comment]
Now i get it. I didn't searh h by item. Yes
My mistake. 

Thank you

**Comment by AnonXS** [comment]
HG = hellground? is pretty outdated at this point, there might be some stuff that we might still be missing but overall always try to query tbc-db first befor posting any sort of "quick" fix which only takes away at our time to look it up for you.

thank you

**Comment by al3xc1985** [comment]
Yes hg is hellground. As i mentioned @AnonXS I did checked as much as I could and from what sources I have at this point.
All i have now my experience from 15 years ago, wowhead, and sites like that. Besides that I check firsr tbx sb to see if info is in there.
Moreover in past, when things started with db vladimir as leader of mangos and all of that point l, it was easier for me to be a developer. I had also sniffs and wdv cache from my official account. But 15 years have past and my knowlwdge in sql feinted.

I am very very sorry to keep you guys busy with this kind of staff. Just wanted to help.
I want to help, but my time ia so little for me, and I try as much as I can to give a hand and starr over tonleqrn to code, relearn the minning od every db with all new features and how to connext to each orher.

Hope this clarify my intentions
Only the besr wishes!
