### ISSUE TITLE
[patch] NPC Text ???

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#757]
Does this tell you something ?
`insert into npc_text (ID, text0_0) values (3,"I do so enjoy sitting out here, listening to the sounds of the Great Sea. Oh, what? Yes, there is a ship that will take you to Menethil Harbor. It docks here from time to time.");
insert into npc_gossip values (8464,3);`

**Comment by Grz3s** [comment]
npc_text **ID** comes from legi source and do not ever choose random one !
BTW:
text exist in npc_text for 'ID = 5579'

**Comment by al3xc1985** [comment]
@Grz3s  thank you. The text is what you said. You are right. Sorry for borhering.  I will try to pay more atention next time.
