### ISSUE TITLE
[Quest Bug] Unexpected Resultds Script Problem

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#764]
So the quest runns very well if you kill the mobs very very very fast, that means that you need to be like 10 level above level 10... but and BUT iif you are low level, as you are normally when you take this quest,  the leash system enters the script end reset mobs script...the system makes the mob to reset and evade and make the script bad and uncompletable.

**Comment by al3xc1985** [comment]
I believe that is a general problem involved here! Why? Because taking in example Anok'suten quest... when you aggro Anok'suten and get him under 50% he must call for help...if you manage to resist all the mobs he aggro after a period of time, those mobs will be afftected by leash system, and thou he, doesn;t get his called help until the end of the fight.

and that is the same thing in Unexpected Resultds quest... Mobs attack minerva and they get affected by leash system.. and that breaks the game mechanic.

**Comment by al3xc1985** [comment]
also an other problem and is a general problem... in quests like this type or escort quests...the npc MUST enter combat with you and help you in fight... fact that does not happend here... it is met in many other quests

**Comment by AnonXS** [comment]
https://github.com/cmangos/mangos-tbc/pull/530

this quest seemingly had issues when it was released, see wowhead comments. newer version of script just make the npcs attack her directly on spawn and they also did not leash for me anymore so that is fixed.
