### ISSUE TITLE
[Quest Bug] Paladin Redemption Quest Chain

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#765]
1. When you summon in the cave the guy you need to kill he should spawn from behind the fire and instantly aggro... Currently he is spawning behind you and doesn't aggrp you
2. Also you should see in the movie how the guy is facing when he stands up. He should face you . Currently you ress him and he has his text of thanks mrs paladin but he doesn't face you... he is with his back towards you

https://www.youtube.com/watch?v=C1KEabu-tAY

**Comment by AnonXS** [comment]
freaking privat server video that is wrong. thats how it was befor it was fixed.
