### ISSUE TITLE
[Quest Bug] Whitebark's Memory

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#766]
In this quest the only problem is that the Old Whitebark when is summoned he must aggro you in first instance... currently it just summon and waits to be aggroed

**Comment by al3xc1985** [comment]
@AnonXS hey can I have you help in here?
I tried to use aggro event and combat_movement action...and many other combinations but not succeded... is it a core limitation to make creature react aggresive ,,,event this react agressive with param 2 does not fix the aggro on summon

**Comment by AnonXS** [comment]
provide some links i dont want to google everything ... thats how you should compose an issue report.

**Comment by al3xc1985** [comment]
ok..one sec

**Comment by al3xc1985** [comment]
https://tbcdb.com/?npc=19456 this is the npc he is summoned  by this item https://tbcdb.com/?item=28209

**Comment by AnonXS** [comment]
any proof he should aggro summoner on spawn? video etc

**Comment by al3xc1985** [comment]
one sec

**Comment by al3xc1985** [comment]
https://www.youtube.com/watch?v=cH973bsf910

**Comment by al3xc1985** [comment]
this is a fast find...but I can find older patches proof...the same fix applies to paladin first trial..when you get in cave and spawn that guy ..he should aggro on spawn

**Comment by al3xc1985** [comment]
blood elf paladin I mean first trial quest

**Comment by AnonXS** [comment]
```
-- Whitebark's Spirit 19456 should attack spawner on spawn
DELETE FROM `dbscripts_on_event` WHERE `id` = 12530;
INSERT INTO `dbscripts_on_event` (`id`, `delay`, `priority`, `command`, `datalong`, `datalong2`, `datalong3`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(12530, 0, 1, 10, 19456, 120000, 0, 0, 0, 0, 0, 0, 0, 0, 8216.55, -6335.38, 64.5098, 3.48, 0, 'Summon Whitebark's Spirit - (Quest 10166)'),
(12530, 0, 0, 26, 0, 0, 0, 19456, 40, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Whitebark's Spirit - Attack Spawner');
``` try this

**Comment by al3xc1985** [comment]
@AnonXS https://www.youtube.com/watch?v=gIfltL1Z97M check this out...he should have also a summon text

**Comment by al3xc1985** [comment]
He sais..
Haven't you done enough harm? Must you also disturb my slumber?

**Comment by AnonXS** [comment]
from second video its visible he doesnt aggro on spawn but moves towards him, no auto aggro

**Comment by al3xc1985** [comment]
ya.. I saw that 2..that he moves toward him and do that line and doesn't aggro in first instance

**Comment by AnonXS** [comment]
```
ServerToClient: SMSG_CHAT (0x2BAD) Length: 136 ConnIdx: 0 Time: 06/12/2017 12:50:11.915 Number: 62294
SlashCmd: 12 (MonsterSay)
Language: 0 (Universal)
SenderGUID: Full: 0x203AF04240130000003FDF00003E71E4 Creature/0 R3772/S16351 Map: 530 Entry: 19456 Low: 4092388
SenderGuildGUID: Full: 0x0
WowAccountGUID: Full: 0x0
TargetGUID: Full: 0x0815D000000000000000000008AF6FB6 Player/0 R1396/S0 Map: 0 Low: 145715126
TargetVirtualAddress: 50528280
SenderVirtualAddress: 50724950
PartyGUID: Full: 0x0
AchievementID: 0
DisplayTime: 0
ChatFlags: 32
HideChatLog: False
FakeSenderName: False
Sender Name: Whitebark's Spirit
Receiver Name: 
Addon Message Prefix: 
Channel Name: 
Text: Haven't you done enough harm?  Must you also disturb my slumber?
```

```
('-10153','Haven''t you done enough harm?  Must you also disturb my slumber?','0','0','0','0','16773','19456'),
('-10154','What good does this violence serve?  What is done is done.  I have failed my people.','0','0','0','0','16774','19456'),
``` we have that not sure what you are on about

**Comment by al3xc1985** [comment]
we might have the line than...but is not set correctly on his spawn moment

**Comment by AnonXS** [comment]
also seems that he always spawns in near proximit of player instead of fixed xyz

**Comment by al3xc1985** [comment]
yes and no I would say no and see this way  
https://www.youtube.com/watch?v=93fRQSR5CZI

**Comment by al3xc1985** [comment]
is more fixed xyz

**Comment by AnonXS** [comment]
yea our acid is wrong there too ty ty

**Comment by al3xc1985** [comment]
and I will do a new report and see something nice in a sec

**Comment by AnonXS** [comment]
yea i see its going deeper should turn friendly quest should be turned in at him instead somwhere else etc etc

**Comment by AnonXS** [comment]
nya it worked quite well at lower levels ok

**Comment by al3xc1985** [comment]
what is nya?

**Comment by AnonXS** [comment]
ah i just killed him which should not be possible, was too high level.

**Comment by al3xc1985** [comment]
also I don't know if this should be possible...
you defeat him...he gest friendly...BUT
you can summon him to infinite by that item and make in the end infinite friendly npc;s of him

**Comment by al3xc1985** [comment]
that is not big deal...because he will despawn after a while

**Comment by AnonXS** [comment]
pull and try now, best i can do for now not sure what causes him to not drop threat on player

**Comment by AnonXS** [comment]
Only issue now is that if player wants to turn quest in they have to run away from mob to drop combat else the quest cant be turned in (button is active at gossip but doesnt work due to being in combat with the same mob where they try to turn in the quest)

**Comment by al3xc1985** [comment]
@AnonXS  please leave it a little bit more open... I will try to work on it a little bit

**Comment by AnonXS** [comment]
as you wish

**Comment by al3xc1985** [comment]
I will come back with news... he must be untargatable in first instance... and he must have that line that I told you about when he spawns

**Comment by al3xc1985** [comment]
https://tbcdb.com/?quest=8889

**Comment by Grz3s** [comment]
hes spawn point `8206.16 -6348.242 64.59447` - static.. always there
then he walks to `8211.638 -6334.247 64.63468` - (he may continue his path after this point.. he may even do circle around that stone.)
- has no unitlags set at spawn - that means:
* - no follow player (faction - 16 : will aggro player if get closer to him)
* - no untargetable flag etc
at spawn he will say his first text (we have this wrong)
at surrender - he will say second text

@AnonXS problem with hight lvl players killing creatures that shouldnt be killed ..was well known
thats why .. on some films you can see players doing quests without weapons or even undressed.
Quest was design for players ~10lvl .. not 70 :)

heres comment from wowhead in this quest:
`By albena (161 – 1) on 2011/06/12 (Patch 4.1.0) 
For those who do this quest on hight level, like lvl80, remember to kill him slowly, best with hands only, till he gets friendly to u, so u can turn in the quest.`

I'll do update tonight for it ..so you can backport it later ;)

**Comment by al3xc1985** [comment]
I rhough5 he is untargetable when he spawns.. I velieves I saw that in a vid... But is was probably spawn moment when npc are untargetable.

Also @AnonXS the part when he aggro at spawn must be removed @Grz3s , this was introducee last night from my mistake

**Comment by al3xc1985** [comment]
@Grz3s can u g8ve me some links were i can find info like wowhead viable. I started again last night to play wow and try to verify each mob that i find and search for movies on youtube about each queat

**Comment by AnonXS** [comment]
the issue is the spawning and that he doesnt move towards player so for the time being its fine as is.

**Comment by Grz3s** [comment]
pls test this:
```sql
-- q.10166 'Whitebark's Memory' - update

-- only one summon at same time available
-- xyz correct and his movement (may not be completed)
DELETE FROM dbscripts_on_event WHERE id = 12530;
INSERT INTO dbscripts_on_event (id, delay, command, datalong, datalong2, datalong3, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(12530,0,31,50,0,0,0,0,0x08,0,0,0,0,0,0,0,0,'(q.10166) only one summon available'),
(12530,10,10,19456,300000,0,0,0,0,0,0,0,0,8206.16,-6348.242,64.59447,0.9,'(q.10166) summon: Whitebark\'s Spirit');
-- source should desp (we want to control this) after quest finished
DELETE FROM dbscripts_on_quest_end WHERE id = 10166;
INSERT INTO dbscripts_on_quest_end (id, delay, command, datalong, datalong2, datalong3, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(10166,0,18,10000,0,0,0,0,0x04,0,0,0,0,0,0,0,0,'(q.10166) despawn source');
UPDATE quest_template SET  CompleteScript = 10166 WHERE entry = 10166;

-- Whitebark's Spirit
UPDATE creature_template SET MovementType = 2 WHERE Entry = 19456;
DELETE FROM creature_movement_template WHERE entry = 19456;
INSERT INTO creature_movement_template (entry, point, position_x, position_y, position_z, orientation, waittime, script_id) VALUES
(19456,1,8211.638,-6334.247,64.63468,0.327416,5000,3); -- this may not be complete path ..but is better than current one we have

-- ACID
-- Whitebark's Spirit 19456
DELETE FROM creature_ai_scripts WHERE creature_id = 19456;
INSERT INTO `creature_ai_scripts` (`id`,`creature_id`,`event_type`,`event_inverse_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`event_param6`,`action1_type`,`action1_param1`,`action1_param2`,`action1_param3`,`action2_type`,`action2_param1`,`action2_param2`,`action2_param3`,`action3_type`,`action3_param1`,`action3_param2`,`action3_param3`,`comment`) VALUES
('1945601','19456','11','0','100','0','0','0','0','0','0','0','1','-10153','0','0','0','0','0','0','0','0','0','0','Whitebark\'s Spirit - Say on Spawn'),
('1945602','19456','0','0','100','1025','13200','13200','23000','37700','0','0','11','31287','1','0','0','0','0','0','0','0','0','0','Whitebark\'s Spirit - Cast Entangling Roots'),
('1945603','19456','0','0','100','1025','27100','27100','30900','38200','0','0','11','11442','1','0','0','0','0','0','0','0','0','0','Whitebark\'s Spirit - Cast Withered Touch'),
('1945604','19456','2','0','100','0','20','0','0','0','0','0','2','35','0','0','24','0','0','0','1','-10154','0','0','Whitebark\'s Spirit - Turn Friendly and Evade and Say At 20% HP');
```

**Comment by al3xc1985** [comment]
it works PERFECT

@AnonXS please push this fix and close it
