### ISSUE TITLE
Hunter Pet Stuck

### ISSUE THREAD

**Issue by lordkj** [cmangos/tbc-db#771]
Hunter pet stuck on doors and stairs. 

Sometimes when  use "stay" command and "follow" he start to move again.

![1](https://user-images.githubusercontent.com/5272572/81152664-d5982c00-8f8a-11ea-80f6-6823585d7095.jpg)
![2](https://user-images.githubusercontent.com/5272572/81152670-d6c95900-8f8a-11ea-8f5b-4472c629ed76.jpg)
![3](https://user-images.githubusercontent.com/5272572/81152671-d761ef80-8f8a-11ea-9595-339c63e810c8.jpg)

**Comment by Dromadoros** [comment]
Hey @lordkj 

I face the same issue, did you find a solution for it ?
