### ISSUE TITLE
[Instance] Scarlet Monastery

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#776]
1. High Inquisitor Whitemane should aggro when she comes from the door behind
2. When you attack Mograine, ALL monastary should be linked and come to attack you

**Comment by evil-at-wow** [comment]
> High Inquisitor Whitemane should aggro when she comes from the door behind

I'm not convinced this is true. I think she just has a very large aggro radius. If you pull Mograine back far enough, she seems to just run out and stay there waiting. At least that's what I remember seeing once, so more research needed.

**Comment by al3xc1985** [comment]
As far s i remember in the chappel, if u keep mograin in chappel she will aggro.. i might not rembwe eirher right

**Comment by Arcalypse** [comment]
### High Inquisitor Whitemane
> As far s i remember in the chappel, if u keep mograin in chappel she will aggro.. i might not rembwe eirher right

This is correct. I have done lengthy research on this one and without getting too far into the specifics of her aggro radius, one thing seems for certain, Whitemane should aggro if you are **anywhere** within the chapel. 

### Videos
**Example 1:** _Chapel Interior - Left Wing_
[https://youtu.be/RupQ_keed_0](https://youtu.be/RupQ_keed_0?t=210) (@ 3:30) - Mar 10, 2007
As shown in the video above, the far-left wing of the cathedral was within her aggro radius.

**Example 2:** _Chapel Interior - Right Wing Room_
[https://youtu.be/JcSxK6Pzvx8](https://youtu.be/JcSxK6Pzvx8?t=185) (@ 3:05) - Jan 8, 2008
The video above shows that her aggro radius includes being in the far-right wing of the chapel room where you have access to [High Inquisitor Fairbanks](https://classic.wowhead.com/npc=4542/high-inquisitor-fairbanks).

**Example 3:** _Chapel Interior - Chapel Doorway_
[https://youtu.be/2AzuJRcSOWg](https://youtu.be/2AzuJRcSOWg?t=215) (@ 3:35) - May 7, 2007
This one was probably the most telling of Whitemane's aggro radius, as you can see the pull executed so cleanly and watch her behavior singularly.

**Example 4:** _Chapel Exterior - Chapel Doorway_
[https://www.youtube.com/watch?v=nj5x3M2qpYQ](https://youtu.be/nj5x3M2qpYQ?t=270) (@ 4:30) - Mar 9, 2008
This is the original upload from this user depicting the pull being performed just outside of the Chapel entrance.

[https://www.youtube.com/watch?v=inOhPKEXmu8](https://youtu.be/inOhPKEXmu8?t=272) (@ 4:32) - Feb 20, 2009
The same user re-uploaded that original video in a higher quality, but I linked the source so there's no doubt on the original upload date.


### Wowhead Comments

From Allakhazam By **Paintedpyro** on **2005/04/29** (_Patch 1.4.0_) Subject: "Make sure you kill everything.."
> Make sure you kill all the Scarlet centurions, monks, abbots, etc. in the building before you attack Mograine. Even the ones to the areas left and right of Mogarine. Once attacked, he will yell and any mobs left will come and assist him.
> 
> Easy to do if know what you're doing. And Whitemane always seems to attack either the lowest level and/or healer with repeated Smite Attacks.


**nevermind3** on **2006/08/22** (_Patch 1.12.0_) Subject: "respawns"
> Seems to me that if you have that many additional scarlets jumping in with the Morgraine fight, you did not clear the whole cathedral before getting his attention.
> 
> The main chamber is a big "T", with small antechambers at the top of the "T".....each of these has a couple of scarlets and the ends of the "T" also has a few standing there.
> 
> All of these should be cleared before taking on Morgraine or else, as you found out, they come to his defense.
>

**Comment by Arcalypse** [comment]
### Scarlet Commander Mograine
> When you attack Mograine, ALL monastary should be linked and come to attack you

I've done a bit of digging and I can confirm that _part_ of this is true. I hate to be picky about the wording but, the entire **Chapel** is aggro'd when you attack Mograine, not the entire **Monastary**. I can confirm this from several videos I've seen like this one below:


### Videos
[https://youtu.be/RupQ_keed_0](https://youtu.be/RupQ_keed_0?t=15) (@ 0:15) - Mar 10, 2007
Not the best quality, but you can see the mage (Level 70) skip aggro'ing any mobs in the courtyard and then simply fight the Chapel mobs from there. Pretty clearly showcases the interaction.

[https://youtu.be/IcM-wVkxJu4](https://youtu.be/IcM-wVkxJu4?t=195) (@ 3:15) - Jun 12, 2007
The video above shows the interaction of the NPCs in the Chapel when Mograine is attacked. You can see that the left-wing, right-wing, and center portions of the entire Chapel come to aid Mograine in the battle.


### Wowhead Comments

From Allakhazam By **Paintedpyro** on **2005/04/29** (_Patch 1.4.0_) Subject: "Make sure you kill everything.."
> Make sure you kill all the Scarlet centurions, monks, abbots, etc. in the building before you attack Mograine. Even the ones to the areas left and right of Mogarine. Once attacked, he will yell and any mobs left will come and assist him.
> 
> Easy to do if know what you're doing. And Whitemane always seems to attack either the lowest level and/or healer with repeated Smite Attacks.


**nevermind3** on **2006/08/22** (_Patch 1.12.0_) Subject: "respawns"
> Seems to me that if you have that many additional scarlets jumping in with the Morgraine fight, you did not clear the whole cathedral before getting his attention.
> 
> The main chamber is a big "T", with small antechambers at the top of the "T".....each of these has a couple of scarlets and the ends of the "T" also has a few standing there.
> 
> All of these should be cleared before taking on Morgraine or else, as you found out, they come to his defense.
> 

From Allakhazam By **Seplaverta** on **2006/11/14** (_Patch 1.12.1_) Subject: "Clear *Everything*"
> You read the title. Clear absolutely EVERYTHING before fighting him. If you don't any remaining mobs in the cathedral (only inside the building) will come and aid him. It will be hell if you leave a few mobs so clear it all! :)

By **TheOnyx** (_78,319 – 28·153·485_) on **2006/11/14** (_Patch 1.12.1_)		
> Mograine is located inside the actual Cathedral in the Cathedral Wing of Scarlet Monastery.
> 
> Before engaging Mograine, make sure you clear out everyone else inside the Cathedral, including the groups in the side wings.
> 
> Once you defeat Mograine, High Inquisitor Whitemane will appear. Once you get her to around 50% health, she'll sleep the entire party, resurrect Mograine, then heal herself. At this point, taking out Whitemane first is advised, since she heals.

**Comment by Arcalypse** [comment]
According to a conversation with **AnonXS** I was advised to mention that when the function `m_creature->CallForHelp(VISIBLE_RANGE);` was re-worked, it likely broke this script.

**Comment by Arcalypse** [comment]
### NPCs
Here is a list of all NPCs that should be pulled when Mograine is aggro'd.

> **Name:** Scarlet Chaplain
> **Guid:** 1890168
> 
> **Name:** Scarlet Centurion
> **Guid:** 1890206
> 
> **Name:** Scarlet Wizard
> **Guid:** 1890184
> 
> **Name:** Scarlet Centurion
> **Guid:** 1890207
> 
> **Name:** Scarlet Champion
> **Guid:** 1890214
> 
> **Name:** Scarlet Centurion
> **Guid:** 1890208
> 
> **Name:** Scarlet Champion
> **Guid:** 1890216
> 
> **Name:** Scarlet Chaplain
> **Guid:** 1890166
> 
> **Name:** Scarlet Centurion
> **Guid:** 1890203
> 
> **Name:** Scarlet Chaplain
> **Guid:** 1890167
> 
> **Name:** Scarlet Centurion
> **Guid:** 1890205
> 
> **Name:** Scarlet Champion
> **Guid:** 1890213
> 
> **Name:** Scarlet Wizard
> **Guid:** 1890185
> 
> **Name:** Scarlet Centurion
> **Guid:** 1890209
> 
> **Name:** Scarlet Wizard
> **Guid:** 1890186
> 
> **Name:** Scarlet Monk
> **Guid:** 1890289
> 
> **Name:** Scarlet Abbot
> **Guid:** 1890221
> 
> **Name:** Scarlet Champion
> **Guid:** 1890212
> 
> **Name:** Scarlet Monk
> **Guid:** 1890288
> 
> **Name:** Scarlet Abbot
> **Guid:** 1890222
> 
> **Name:** Scarlet Abbot
> **Guid:** 1890223
> 
> **Name:** Scarlet Monk
> **Guid:** 1890292
> 
> **Name:** Scarlet Champion
> **Guid:** 1890215
> 
> **Name:** Scarlet Abbot
> **Guid:** 1890224
> 
> **Name:** Scarlet Monk
> **Guid:** 1890291
> 
> **Name:** Scarlet Abbot
> **Guid:** 1890225
> 
> **Name:** Scarlet Champion
> **Guid:** 1890217
> 
> **Name:** Scarlet Monk
> **Guid:** 1890290
> 
> **Name:** Scarlet Wizard
> **Guid:** 1890189
> 
> **Name:** Scarlet Wizard
> **Guid:** 1890188
> 
> **Name:** Scarlet Chaplain
> **Guid:** 1890169
> 
> **Name:** Scarlet Centurion
> **Guid:** 1890211
> 
> **Name:** Scarlet Chaplain
> **Guid:** 1890170
> 
> **Name:** Scarlet Monk
> **Guid:** 1890295
> 
> **Name:** Scarlet Champion
> **Guid:** 1890220
> 
> **Name:** Scarlet Monk
> **Guid:** 1890293
> 
> **Name:** Scarlet Monk
> **Guid:** 1890294
> 
> **Name:** Scarlet Champion
> **Guid:** 1890218
> 
> **Name:** Scarlet Wizard
> **Guid:** 1890187
> 
> **Name:** Scarlet Champion
> **Guid:** 1890219
> 
> **Name:** Scarlet Centurion
> **Guid:** 1890210
> 
> **Name:** Scarlet Monk
> **Guid:** 1890296

**Comment by insunaa** [comment]
Fixed in https://github.com/cmangos/mangos-tbc/commit/ca85a00ed9babae5a54b628c6bf1bc8c4a3978f5

**Comment by killerwife** [comment]
All issues in thread resolved?

**Comment by insunaa** [comment]
Yes
