### ISSUE TITLE
[Event] Ashbringer Event Does not trigger when you weild Corrupted Ashbringer

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#777]
As the title suggest somethign went wrong with the script during time, from the moment when it was implemented until today... maybe is just me... 
I went today with corrupted into the monastary and all mobs are enemy and not friendly as it should.

I recommand to devs to get a new big full release, there are MANY updates, and somehow the installer miss some of them

**Comment by al3xc1985** [comment]
also I am sure that many startup errors would dissapear... currently I have many startup errors... but I do not report them yet considering killer, anonxs, and saltgurta remarks with many many backports coming in the near feature from vengeance wow, that would fix most of the errors, as I understood.If I am wrong in any of my concern or statements please correct me.. thank you in advance

**Comment by al3xc1985** [comment]
https://www.reddit.com/r/classicwow/comments/ai3f0h/scarlet_monastery_corrupted_ashbringer_event/

here are some new info about the event...
Bonus: If you went to LH Chapel in the Eastern Plaguelands with the Corrupted Ashbringer equipped than you would temporarily become Hated with the Argent Dawn

**Comment by MantisLord** [comment]
It appears to be working to me now @al3xc1985 can you confirm on latest core/db?

**Comment by al3xc1985** [comment]
I can't test right now, my monitor is not working for me from my computer. I allready ordered one...when it comes I shall test and give back feedback, and eventually close this

**Comment by AnonXS** [comment]
confirmed working
