### ISSUE TITLE
Missing NPC Conversation

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#784]
I might be wrong, but I can't find them having this talk

Ley-Keeper Caidanis
https://www.wowhead.com/npc=15405/ley-keeper-caidanis
Prospector Anvilward
https://www.wowhead.com/npc=15420/prospector-anvilward

Here we have a movie where we can see their small talk, before player activate the prospector anviward gossip
```
-- https://youtu.be/zfOLeExhKh0?t=58
```

I would love to learn to script it, if you guys can tell me in what tables should I give it a shot!
I tried like 10 hours to find anything in documentation but nothing

**Comment by Grz3s** [comment]
Best way to script this is to use EAI+DBscripts...
https://github.com/cmangos/issues/wiki/creature_ai_scripts
https://github.com/cmangos/issues/wiki/DBScripts

What we want here is:
EAI - will give us Random times between its occurrence... Most of these kind of tiny events repeats between 3-6 (later expansions even up to 10mins)
So:
Use here EAI (OOC) - out of comabat.
` creature_ai_scripts
('(ENTRY)01','(ENTRY)','1','0','100','1','10000','60000','180000','300000','0','0', ......`
to understand this - i would recoment read about how EAI works (belive me its not hard)
- you can see here its set up .. on ooc .. with 100% chance.. repeats flag ..and times are set:
- 10000 - 60000 (range for first apperiance - its set in ms)
- 180000 - 300000 (repeats between 3 - 5mins) 

To link it with DB Scripts - You need to use EAI ACTION Type - 53  ACTION_T_START_RELAY_SCRIPT
`....'53','A'....  .... ,'NPC NAME - START_RELAY_SCRIPT on OOC timer'),`

And now we can jump to DB_SCRIPTS....
`DELETE FROM dbscripts_on_relay WHERE id = A);
INSERT INTO dbscripts_on_relay (id, delay, command, datalong, datalong2, datalong3, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
- use here commands
- 0 - for texts for master and for buddy
- 31 - to check if other npc is around
You'll find many scripts like this one in TDB or WoTLK updates:
https://github.com/cmangos/wotlk-db/tree/master/Updates
https://github.com/cmangos/tbc-db/tree/master/Updates

**Comment by al3xc1985** [comment]
Ty very much. I will get my hands on this to script it up at the end of the week.. I will come back with info ty ty ty @Grz3s
