### ISSUE TITLE
Apprentice Veya 3 random gossips missing

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#785]
According to wowhead: 
https://www.wowhead.com/npc=15946/apprentice-veya#comments

She should have 3 random texts when you talk with her.. currently she has none:
Run along pest
Not very intelligent are you?
I do not suffer fools gladly

**Comment by Grz3s** [comment]
Im sory to disappoint you .. but:
In pre Cata sniffs (Source: 03/05/2010) -- she hasnt got any npcflag set. this means - no gossip , no quest giver etc)

For future pls make sure about few things:
- check info (data) that is pre Cata (so before DEC.2010)
- comment you ref. here comes from Cata times (4.x.x)

I saw You ref. in other places also YT avis and other info from later expansions .. that may not be valid for TBC or even for WoTLK. Pls revisit and correct them.

**Comment by al3xc1985** [comment]
I will try my best and recheck them.. ty very much for info

**Comment by al3xc1985** [comment]
Checked again...and you are right...
Close it!
