### ISSUE TITLE
NPC visible only to GM is also visible to players

### ISSUE THREAD

**Issue by aleigood** [cmangos/tbc-db#789]
nagrand spawn trigger (18263) is always visible to normal players.
![image](https://user-images.githubusercontent.com/3367999/83270405-002c7c00-a1fb-11ea-8282-c2e97e3a2f2c.png)

**Comment by al3xc1985** [comment]
write down a gps so devs know where to check

**Comment by aleigood** [comment]
creature id is already on it.
.go cr id 18263

**Comment by Arcalypse** [comment]
### LOCATION OF ISSUE
The zone @al3xc1985 was referring to is **Halaa** in **Nagrand**.
Developers may use the following teleport command to get there:
`.tele Halaa`

or alternatively, here are the GPS.

**MAP:** 530 (Outland)
**ZONE:** 3518 (Nagrand)
**AREA:** 3628 (Halaa)
**X:** -1571.06
**Y:** 7941.85
**Z:** -22.41
**ORIENTATION:** 0.00

### SUGGESTED FIX
I was able to fix this by applying the "_CREATURE_EXTRA_FLAG_INVISIBLE_" (128) flag to this creature. The SQL script can be found below:

`-- NPC NAME: Nagrand Spawn Trigger
-- ENTRY: 18263
-- FIX: Applied "CREATURE_EXTRA_FLAG_INVISIBLE" ExtraFlag to make creature invisible.
UPDATE `creature_template` SET `ExtraFlags` = 128 WHERE `entry` = 18263;`


### BEFORE
![image](https://user-images.githubusercontent.com/71293537/93708797-27d78500-fb07-11ea-8531-110579efccf0.png)

### AFTER
![image](https://user-images.githubusercontent.com/71293537/93708810-4473bd00-fb07-11ea-93d4-5d0807f75e75.png)

**Comment by Grz3s** [comment]
can't reproduce it on Wotlk...
Can someone check TBC AND Classic ?

**Comment by Xadras** [comment]
I checked tbc and the problem still exists there. (classic don't have halaa)

**Comment by Grz3s** [comment]
haha youre correct :D
