### ISSUE TITLE
Netherwing Daily bugged

### ISSUE THREAD

**Issue by Jekalemoeder** [cmangos/tbc-db#797]
Can't recall the name of the specific quest, but you have to poison peon's camps using a mutton and fel glands. The Fel Glands are obtained from random beasts in SMV and have a low droprate. The quest is bugged in that in stead of poisoning a complete camp of peons, it only attracts one. Therefor you'll need 12 of the Fel Glands which is very time consuming and unintended. I have attached two screenshots that show the bug. You can see clearly that there are enough peons in range, but just one goes to the mutton.
![Peons 1](https://user-images.githubusercontent.com/55199354/88204572-c0f33800-cc4b-11ea-9522-b504c2e15414.png)

![Peon 2](https://user-images.githubusercontent.com/55199354/88204568-bfc20b00-cc4b-11ea-9959-8fc2c3ee1bd9.png)

**Comment by killerwife** [comment]
Where does it say it should attract all of them?

**Comment by Jekalemoeder** [comment]
In every way the quest referes to multiple mobs and tells you to ‘Poison
the camps’
https://tbc-twinhead.twinstar.cz/?quest=11020
Also the wowhead screenshots and comments clearly speak about tagging
multiple peons:
https://www.wowhead.com/quest=11020/a-slow-death#comments


Op wo 22 jul. 2020 om 19:33 schreef killerwife <notifications@github.com>

**Comment by AnonXS** [comment]
https://www.wowhead.com/quest=11020/a-slow-death#comments:id=87543:reply=298568

```

7 | Toabo on 2007/05/22  (Patch 2.1.0)
This  quest is the most conducive to grouping of the Neutral->Friendly  series. 

All you need is a total of 12 Fel Glands for your entire group.   <----
 (For example, if you have 5 and your buddy has 7, you're good to go.) 

 Once you've got that, fly back and have one (and only one) person use  Yarzill's Mutton near a peon camp.  
The peons will wander over, eat the  meat, and die.  Everyone in the group who is nearby will get credit.
Do not have more than one person use the Mutton per camp.
The peons  will only eat the first one, so you won't get credit for the second one  and you'll have to farm anot
```

**Comment by Arcalypse** [comment]
I am not an expert and cannot seem to find a fix for this anywhere on the internet already; but, I have a suspicion that this might be an issue related to the way this particular quest was written in the **shadowmoon_valley.cpp** file. This file can be located here:

`./src/game/AI/ScriptDevAI/scripts/outland/shadowmoon_valley.cpp`

Below is a copy of the **npc_dragonmaw_peon** script itself. This script ranges from lines _294_ to _429_.

`/*#####
# npc_dragonmaw_peon
#####*/

enum
{
    SAY_PEON_1                      = -1000652,
    SAY_PEON_2                      = -1000653,
    SAY_PEON_3                      = -1000654,
    SAY_PEON_4                      = -1000655,
    SAY_PEON_5                      = -1000656,

    SPELL_SERVING_MUTTON            = 40468,
    NPC_DRAGONMAW_KILL_CREDIT       = 23209,
    EQUIP_ID_MUTTON                 = 2202,
    POINT_DEST                      = 1
};

struct npc_dragonmaw_peonAI : public ScriptedAI
{
    npc_dragonmaw_peonAI(Creature* pCreature) : ScriptedAI(pCreature) { Reset(); }

    ObjectGuid m_playerGuid;
    uint32 m_uiPoisonTimer;
    uint32 m_uiMoveTimer;
    uint32 m_uiEatTimer;

    void Reset() override
    {
        m_playerGuid.Clear();
        m_uiPoisonTimer = 0;
        m_uiMoveTimer = 0;
        m_uiEatTimer = 0;

        SetEquipmentSlots(true);
    }

    bool SetPlayerTarget(ObjectGuid playerGuid)
    {
        // Check if event already started
        if (m_playerGuid)
            return false;

        m_playerGuid = playerGuid;
        m_uiMoveTimer = 500;
        return true;
    }

    void MovementInform(uint32 uiType, uint32 uiPointId) override
    {
        if (uiType != POINT_MOTION_TYPE)
            return;

        if (uiPointId == POINT_DEST)
        {
            m_uiEatTimer = 2000;
            m_uiPoisonTimer = 3000;

            switch (urand(0, 4))
            {
                case 0: DoScriptText(SAY_PEON_1, m_creature); break;
                case 1: DoScriptText(SAY_PEON_2, m_creature); break;
                case 2: DoScriptText(SAY_PEON_3, m_creature); break;
                case 3: DoScriptText(SAY_PEON_4, m_creature); break;
                case 4: DoScriptText(SAY_PEON_5, m_creature); break;
            }
        }
    }

    void UpdateAI(const uint32 uiDiff) override
    {
        if (m_uiMoveTimer)
        {
            if (m_uiMoveTimer <= uiDiff)
            {
                if (Player* pPlayer = m_creature->GetMap()->GetPlayer(m_playerGuid))
                {
                    GameObject* pMutton = pPlayer->GetGameObject(SPELL_SERVING_MUTTON);

                    // Workaround for broken function GetGameObject
                    if (!pMutton)
                    {
                        const SpellEntry* pSpell = GetSpellStore()->LookupEntry<SpellEntry>(SPELL_SERVING_MUTTON);

                        uint32 uiGameobjectEntry = pSpell->EffectMiscValue[EFFECT_INDEX_0];

                        // this can fail, but very low chance
                        pMutton = GetClosestGameObjectWithEntry(pPlayer, uiGameobjectEntry, 2 * INTERACTION_DISTANCE);
                    }

                    if (pMutton)
                    {
                        float fX, fY, fZ;
                        pMutton->GetContactPoint(m_creature, fX, fY, fZ, CONTACT_DISTANCE);

                        m_creature->SetWalk(false);
                        m_creature->GetMotionMaster()->MovePoint(POINT_DEST, fX, fY, fZ);
                    }
                }

                m_uiMoveTimer = 0;
            }
            else
                m_uiMoveTimer -= uiDiff;
        }
        else if (m_uiEatTimer)
        {
            if (m_uiEatTimer <= uiDiff)
            {
                SetEquipmentSlots(false, EQUIP_ID_MUTTON, EQUIP_UNEQUIP);
                m_creature->HandleEmote(EMOTE_ONESHOT_EAT_NOSHEATHE);
                m_uiEatTimer = 0;
            }
            else
                m_uiEatTimer -= uiDiff;
        }
        else if (m_uiPoisonTimer)
        {
            if (m_uiPoisonTimer <= uiDiff)
            {
                if (Player* pPlayer = m_creature->GetMap()->GetPlayer(m_playerGuid))
                    pPlayer->KilledMonsterCredit(NPC_DRAGONMAW_KILL_CREDIT, m_creature->GetObjectGuid());

                m_uiPoisonTimer = 0;

                // dies
                m_creature->SetDeathState(JUST_DIED);
                m_creature->SetHealth(0);
            }
            else
                m_uiPoisonTimer -= uiDiff;
        }

        DoMeleeAttackIfReady();
    }
};`

I'll keep looking into this one, but my thought is that somehow with the way this logic is structured, it's only targeting a **single** creature to eat the poisoned mutton, versus multiple within the acceptable radius. I know this might seem very obvious given the description of the error itself, but I'm hoping if someone else comes along and can figure it out sooner than me, that this will be helpful to them.

**Comment by killerwife** [comment]
There I did my research, blizzard had an aoe effect during 2.1 and later changed it to single target. So non-issue.
