### ISSUE TITLE
Using shadowstep talent the char does not face the back

### ISSUE THREAD

**Issue by kderholt** [cmangos/tbc-db#801]
When you use this spell the char should face the back of the mob, atm its just facing w/e the char currently faces.

https://www.youtube.com/watch?v=5og8jk3oxCE

**Comment by arowjet** [comment]
spelleffects.cpp

effectteleportunits

`    // Teleport
	if (m_targets.m_mapId == UINT32_MAX || m_targets.m_mapId == unitTarget->GetMapId())
	{
		unitTarget->NearTeleportTo(x, y, z, unitTarget->GetTarget()->GetOrientation(), unitTarget == m_caster);
		if(unitTarget->HasTarget())
			unitTarget->NearTeleportTo(x, y, z, unitTarget->GetTarget()->GetOrientation(), unitTarget == m_caster);
		else
			unitTarget->NearTeleportTo(x, y, z, orientation, unitTarget == m_caster);`

**Comment by kderholt** [comment]
thank you, how did dig yoruself into that this is the effect of shadowsteps

**Comment by arowjet** [comment]
just did some tests on the server and read through all the function names for proper effect :)
