### ISSUE TITLE
dungeon old hillsbrad foothills

### ISSUE THREAD

**Issue by k4s1pro** [cmangos/tbc-db#804]
hi after releasing thrall we go out and captain skarloc shows up but does nothing, you cant hit him and try in heroic and normal mode.
[https://demondark.es/old.png](url)

**Comment by tangko5290** [comment]
![20210216104658](https://user-images.githubusercontent.com/77279936/108012502-82d4c000-7044-11eb-9839-38c85db3be3b.png)
I have this problem, too.It should be that the dialog script did not trigger.However, after using the '. Die' management command to kill captain skarloc, the plot will trigger normally

**Comment by AnonXS** [comment]
![grafik](https://user-images.githubusercontent.com/19734826/133325099-4692e3bc-de4d-42ee-8a59-3a15fda4cae4.png)


(17876,0,37,2063.4,229.509,64.4883,0,5000,0,'attack Skarloc'),

            case 37:
                // Allow the guards and Skarloc to attack
                if (Creature* pSkarloc = m_pInstance->GetSingleCreatureFromStorage(NPC_SKARLOC))
                {
                    pSkarloc->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PLAYER);
                    pSkarloc->AI()->AttackStart(m_creature);
                    AttackStart(pSkarloc);
                }

He could use some orientation = 100 or actual orientation values on some waypoints though.

**Comment by al3xc1985** [comment]
@AnonXS I remember that this was fixed at some point, am I right?

**Comment by AnonXS** [comment]
probably related to the point = 0 changes

<https://github.com/cmangos/mangos-tbc/commit/026bf8f50f30edf2e04124ad2eafcba63a753df3>
