### ISSUE TITLE
Quest The Last Barow 5344 - missing startscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#812]

**Comment by Grz3s** [comment]
Confirmed with KW... it was about horde version:
https://classic.wowhead.com/quest=5342/the-last-barov
Fixed

**Comment by killerwife** [comment]
Also alliance has one.

**Comment by killerwife** [comment]
Alliance:
ServerToClient: SMSG_EMOTE (0x2814) Length: 16 ConnIdx: 1 Time: 09/20/2020 16:32:50.117 Number: 358137
GUID: Full: 0x2045AC00000AC3C000004D0000672E44 Creature/0 R4459/S77 Map: 0 Entry: 11023 Low: 6762052
Emote ID: 22 (OneShotShot)

Sender Name: Weldon Barov
Receiver Name: 
Channel Name: 
Text: The fortune is mine, Alexi! Your end comes soon!
