### ISSUE TITLE
Sister of Grief

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#813]
Shouldn't she have also Whipped Fury?

https://www.wowhead.com/npc=16960/sister-of-grief#abilities
or it is introduced in 4.0.3? @AnonXS

**Comment by AnonXS** [comment]
![Unbenannt](https://user-images.githubusercontent.com/19734826/116484257-fdae2880-a888-11eb-99b2-6405142212f4.PNG)

think this npc was heavly modified over the course of expansions, the last ability, absorb life reads heavily overpowered for the level (60-61 mob where players have about-less hp then the drained value). s.34036/34239

they probably aligned the mob with the other sisters in the zone so it feels less "random" what they do.
