### ISSUE TITLE
Quest "The road to falcon watch" missing text

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#814]
There is a text missing (untraslated) in the quest at some point when u escort the pilgrim blood elf to falcon watch
Image
![WoWScrnShot_011521_215813](https://user-images.githubusercontent.com/6240049/104773223-627fc000-577d-11eb-960a-9bc420ecedd3.jpg)

**Comment by al3xc1985** [comment]
@Lymphome can u check this one pls?

**Comment by AnonXS** [comment]
Seemingly resolved with https://github.com/cmangos/mangos-tbc/commit/21eabd452ebdc09e81f1cb543e7bf98fe563eaae
