### ISSUE TITLE
Quest 1787 and 1784 - Tome of Divinity - ressurect script

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#837]
One is dwarven and one is human

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/ea2d94bef7b4b7a46a1d6df71ad457a872f41fea
https://github.com/cmangos/mangos-tbc/commit/cdd18a1055fda97a22f5006eb47516bd43a8e171
