### ISSUE TITLE
NPC 7136 - Infernal Sentry - missing waypoints

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#861]

**Comment by Tobschinski** [comment]
https://github.com/cmangos/classic-db/commit/f1d7f86366fb36ab3f4a79693bb7f27504e8c73a

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/22025fc9d26cfbad88b29e846d4bc37ffbdeb595
