### ISSUE TITLE
Quest 3914 - Grave Situation - afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#867]
This object https://classic.wowhead.com/object=148504/a-conspicuous-gravestone should glow either at end or start of next quest

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/issues/971
Double?

**Comment by al3xc1985** [comment]
I guess he wanted to say :Linken's Sword: quest @killerwife 

3913 is #971

**Comment by killerwife** [comment]
Yep double.
