### ISSUE TITLE
Quest 465 - Nek'rosh's Gambit - missing afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#889]
Catapult starts burning

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/2a8542b6baf94c0d8c7d2ecc7f3f55a20a661570

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/commit/58d757c95b7c944654ef5bdd733162821dcf903b
