### ISSUE TITLE
Quest 7461 - The Madness Within - afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#892]
These spawn and do stuff https://www.wowhead.com/npc=14364/shendralar-spirit#comments

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/d062e86d56025b9505e6b3e7d870e92860a23e99

**Comment by miraco** [comment]
This looks a bit tricky to add in cmangos.
Vmangos has the option to let the spawned creature have an individual script.
If i understand this script right, 8 npcs with id 14364 get spawned, and all of them should handle an differnt script.

Do we have a way to do this in cmangos? 
SCRIPT_COMMAND_TERMINATE_SCRIPT uses entry, so every npc will use it.

Then i changed my local code to:
![ss+(2021-12-06+at+03 10 42)](https://user-images.githubusercontent.com/6261245/144860949-3d6de683-38b5-4b5d-80a4-a3b4854300ed.png)
Imo we can add relayScript as dataint 4 so we can specify different relay scripts for spawned creatures with same entry id.

@killerwife  whats your opinion to this?

**Comment by killerwife** [comment]
@miraco how is the npc spawned?

**Comment by miraco** [comment]
They get spawned via db_quest_end_script. They dont move, just change facing to the player, and do some emote.

**Comment by killerwife** [comment]
Ok, I know what we need for this, I will code a feature real quick, rework some existing stuff and ping it here.

**Comment by miraco** [comment]
> Ok, I know what we need for this, I will code a feature real quick, rework some existing stuff and ping it here.

Okay, just in case:
https://github.com/vmangos/core/commit/0f8ce721da882766f33e499ae7997f7a10802d1e

For this script 
NPCs get spawned via db_quest_end_script. And after some time they will move and cast a spell.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/commit/806bcbfaca32ee19fca6b4d30f08c5ab39936db8
https://github.com/cmangos/tbc-db/commit/526fb9c97f2023c65e8b124ccb6e42bab51636e7
https://github.com/cmangos/tbc-db/commit/ebb8294e554c173a7089b715806fe25ea029672a

Note: numbering scheme for spawn data template - vanilla uses 100-9999 range, 10000+ is for tbc, this is so we dont have overlap.

**Comment by miraco** [comment]
Thanks for your work.

Do i understand it right, that i have to "pre" spawn them in table creature setting spawntimesecsmin and spawntimesecsmax to 0, set spawn_data_template with the relaay script and then "respawn" them via dbscripts_on_quest_end SCRIPT_COMMAND_RESPAWN

**Comment by killerwife** [comment]
No, merely you need to add creature_spawn_data_template which can be filled in dbscript command 10 spawn creature for dataint4

**Comment by miraco** [comment]
Okay, thats working. Thanks.
I think i should stop thinking so complicated sometimes, or my brain already damaged to much for today... xD

**Comment by Grz3s** [comment]
i just looked at vid from this quest... they all summon in same time... (didnt see facing player) and if im correct... they all doing some random emotes... 
So i would use command 10 temp summon creature... + EventAI (repeat every Xsecs depends on whats in sniff)  `10  ACTION_T_RANDOM_EMOTE ` on spawn .. u can use all 3 actions which gives you 9 random emotes in total... or if theyre more then use random_templates
BTW: u can also set face summoner on spawn ..if its the case there. (but i didnt see it on vid)

**Comment by miraco** [comment]
Thats something you have to ask @ratkosrb 
Im just trying to implement the scripts from vmangos into cmangos. 
Just thought about what will happen when more then 1 player complete the quest, he doesnt have any check for this. So we would have multiple spawn on same positions, worst case all 5 players complete the Quest, all 8 npcs getting spawned 5 times.

Only from logical thinking i would add a check if one of the npcs already spawned. If not go ahead, if one is spawned stop the script.

**Comment by killerwife** [comment]
All of the recent commits by @ratkosrb are sourced either from my or his sniffs. So even if its supposed to be a bit more random, its definitely not wrong.

**Comment by ratkosrb** [comment]
> Just thought about what will happen when more then 1 player complete the quest, he doesnt have any check for this. So we would have multiple spawn on same positions, worst case all 5 players complete the Quest, all 8 npcs getting spawned 5 times.

I do have a check for that. Only 8 can be spawned at the same time. And since they spawn simultaneously and have the same despawn delay, only one set of spirits will be up at any given time.
![Untitled](https://user-images.githubusercontent.com/35845488/145021277-80a7c5f3-6d7d-4067-a509-bf072fc9b375.jpg)
.

**Comment by killerwife** [comment]
Dbscripts on end have "Script execution unique by source." which means the script wont be reexecuted if someone else finishes it while your script is running.

**Comment by miraco** [comment]
> Dbscripts on end have "Script execution unique by source." which means the script wont be reexecuted if someone else finishes it while your script is running.

You sure about this? I just tested ingame with 2 characters and npcs got double spawned, thats why implemented a check for this.
Afaik we dont have it like vmangos "unique temporary spawn"

**Comment by killerwife** [comment]
Yes because you delegate the script from end script to relay script, once its on the relay script, there isnt a "unique" condition running anymore. Add something at the end, like a terminate condition at like 28 seconds for the dbscripts_on_end and it will work as intended. Your script as is ends at 0 delay. However your solution with the condition is also valid. Just mentioning this going forward.

**Comment by Grz3s** [comment]
`Thats something you have to ask @ratkosrb` 😄 ok 

`I do have a check for that. Only 8 can be spawned at the same time. And since they spawn simultaneously and have the same despawn delay, only one set of spirits will be up at any given time.`
use:
```code
INSERT INTO dbscripts_on_quest_end (id, delay, command, datalong, datalong2, datalong3, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(xxxx,1,31,14364,50,0,0,0,0x08,0,0,0,0,0,0,0,0,'search for 14364 - terminate if alive'),
... rest of your script
```
will prevent multispawn

**Comment by miraco** [comment]
Yeah that's how I already did it :)
Never worked with vmangos and didn't see that you checked it that way :/

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/commit/bb7fc2b541732900979e591e3a6459934724f45d
