### ISSUE TITLE
Sealed tome buffs stay active outside of karazhan.

### ISSUE THREAD

**Issue by Saben65** [cmangos/tbc-db#9]
> Looting the object has one of two results:
> 1. Places one of four books in your inventory, which, when used, grant certain buffs for 60 minutes. The books disappear when you leave Karazhan (and you of course lose the buff when you die).
> [Source: WoW Wiki](http://wowwiki.wikia.com/wiki/Sealed_Tome)

http://www.wowhead.com/spell=30550/redemption-of-the-fallen
http://www.wowhead.com/spell=30557/wrath-of-the-titans
http://www.wowhead.com/spell=30562/legacy-of-the-mountain-king
http://www.wowhead.com/spell=30567/torment-of-the-worgen

Suggested Fix
```SQL
-- Limit Karazhan book buffs to inside the raid.
DELETE FROM `spell_area` WHERE `spell` IN (30550,30557,30562,30567);
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_start_active`, `quest_end`, `condition_id`, `aura_spell`, `racemask`, `gender`, `autocast`) VALUES 
(30550, 3457, 0, 0, 0, 0, 0, 0, 2, 0), -- Redemption of the Fallen
(30557, 3457, 0, 0, 0, 0, 0, 0, 2, 0), -- Wrath of the Titans
(30562, 3457, 0, 0, 0, 0, 0, 0, 2, 0), -- Legacy of the Mountain King
(30567, 3457, 0, 0, 0, 0, 0, 0, 2, 0); -- Torment of the Worgen
```

**Comment by killerwife** [comment]
Closed in https://github.com/cmangos/tbc-db/commit/6ba206588a58d7fb021d7d27353d364f8b630297
