### ISSUE TITLE
NPC 3204 - Gazz'uz - multiple pooled spawns

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#908]
Easy because no movement. Just multiple spawns I counted 3.

**Comment by Tobschinski** [comment]
https://github.com/cmangos/classic-db/commit/09306789ff4bfbf27a7b47e6ce62f268be1e4bfd

**Comment by killerwife** [comment]
You got the spawns yourself? Cos I had some sniff.

**Comment by Tobschinski** [comment]
Yep.

**Comment by Tobschinski** [comment]
apparently there are (at least) 4
https://github.com/cmangos/classic-db/commit/245d35e3fce20ffdae13c0f4f00b2f923510821a

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/6266676562d5f45ee14845c4eedd60f1e5bec021
https://github.com/cmangos/tbc-db/commit/830ee1097d70b110158f7ea48a6f7126f81e9f4c
