### ISSUE TITLE
Quest 772 - Rite of Vision - missing LOS script

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#911]
Seer Wiserunner https://classic.wowhead.com/npc=2984/seer-wiserunner#ends does a text when player approaches him before turning in quest.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/291656daa69b6b8f1e4d30417c09a56ae6203097

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/commit/57d0d88d48c67a251cf6a335f9c4350e6a748f82
