### ISSUE TITLE
NPC 3056 - Ghost Howl - missing path

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#912]
We have two northern paths, and miss one southern path. Do not have data on it because it is usually dead.

**Comment by Tobschinski** [comment]
https://github.com/cmangos/classic-db/commit/cbe8560ed6772406aa0bd6486b21546eb961610d

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/8ce79183e82049dcd793ceaa42576bbd46277de7

guid
51845
51854
1007218

https://tbc.wowhead.com/npc=3056/ghost-howl#map
