### ISSUE TITLE
NPC 7135 - Infernal Bodyguard - missing spawns

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#922]
0 in db, counted at least 2

**Comment by Tobschinski** [comment]
https://github.com/cmangos/classic-db/commit/5c9a3870eea0a310d91f66d947d2412514e6bdb1

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/ac0d31d23dbba4fa9201c2834e6394e85497b12e
