### ISSUE TITLE
event mobs stacking

### ISSUE THREAD

**Issue by Phatcat** [cmangos/tbc-db#93]
![tbc](https://user-images.githubusercontent.com/1907820/27280371-fb8ad4ca-54e7-11e7-8104-b6551637412e.JPG)

(Classic)
![classic](https://user-images.githubusercontent.com/1907820/27280394-0cf2148a-54e8-11e7-93de-aa4be2009ea8.JPG)

(WOTLK)
![wotlk](https://user-images.githubusercontent.com/1907820/27280406-15801f48-54e8-11e7-853d-04a4aff3c8b0.JPG)

**Comment by AnonXS** [comment]
seems there are cross db conflicts with this pull: https://github.com/cmangos/tbc-db/pull/62

**Comment by evil-at-wow** [comment]
It's not related to that pull/commit, because I've seen those mobs stack for years in TBC. I'm sure TBC-DB versions as old as 1.4 have it as well.

**Comment by MantisLord** [comment]
The issue here most likely has to do with game_event entries as @AnonXS suggested.
Occurrence of the events in WDB is 60480 but only 5760 in TBC-DB.

If you were to list your events, it should show all of the Call to Arms events are running simultaneously. I'll try to correct this soon.

**Comment by AnonXS** [comment]
Problem is, all pvp game events are active on core startup, making all spawns related to these pvp gameevents spawned. This is just visual and will not be like this in a live Experience and can be deactivated by deactivating the game event ingame.

**Comment by killerwife** [comment]
Closed in 6efd76d7828d746f6f584ca24932c61208042f9c
