### ISSUE TITLE
Rexxar is named Rokaro

### ISSUE THREAD

**Issue by Logonz** [cmangos/tbc-db#934]
It seems like rexxar is named Rokaro across the Database.
I would guess it is due to Retail having named the mob Rokaro instead of Rexxar but they still keep the same ID.

https://www.wowhead.com/npc=10182/rokaro
https://classic.wowhead.com/npc=10182/rexxar
https://tbc.wowhead.com/npc=10182/rokaro

**Comment by killerwife** [comment]
This is correct, rexxar moved to tbc zone in tbc.
