### ISSUE TITLE
Extra creature that need deleted

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#940]
![WoWScrnShot_073121_194658](https://user-images.githubusercontent.com/6240049/127746762-e18e90a1-864b-4464-9bfe-b6040b02210d.jpg)

The Nethergarde Infantry should not be spawned there...he is spawned by script only...and the script is working as far as I saw...

And the way the script works is like this:
He spawns, go get a horse, and ride until DoomLord at the dark portal, where he despawns... is that correct?

**Comment by AnonXS** [comment]
i recently deleted that npc

**Comment by al3xc1985** [comment]
I will wait and retest and close this

**Comment by AnonXS** [comment]
yea no i sorted that file out, will export the tbc part now to close this.

**Comment by al3xc1985** [comment]
ok...close it
