### ISSUE TITLE
NPC 486 -  Tharil'zun - missing path

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#942]
Very infrequent patrolling with his companion caster or warrior.

**Comment by al3xc1985** [comment]
@Tobschinski hey toby can u get this, it;s a nice catch. I believe his 2 guards are linked to him

**Comment by Tobschinski** [comment]
have already done it

**Comment by al3xc1985** [comment]
ok..ty. I am waiting for the fix when u got time of course...

ty again toby @Tobschinski

**Comment by al3xc1985** [comment]
@Tobschinski can u share pls this info? I would love to see this guy scripted

**Comment by AnonXS** [comment]
https://github.com/vmangos/core/commit/b112e363862e005ce32a781867edfeefcb3431cc - giyf

**Comment by al3xc1985** [comment]
@AnonXS  U ARE MY hero!

**Comment by Tobschinski** [comment]
Can't commit anything myself, formations don't exist yet.

**Comment by cyberium** [comment]
You can commit on my DB

**Comment by Tobschinski** [comment]
Sorry, no scriptable groups there, but ... I'll check again in a year or so.
