### ISSUE TITLE
Enchanting Item - Trade Window

### ISSUE THREAD

**Issue by Naraku93** [cmangos/tbc-db#949]
enchants for other players are instant spells, but there should have the same cast time as when enchant own weapons

**Comment by killerwife** [comment]
Evidence for that?

**Comment by Naraku93** [comment]
> Evidence for that?

look at other server's. that's not new.  i only know that way

**Comment by killerwife** [comment]
Thats not valid evidence. Proof from blizzard servers is required.

**Comment by insunaa** [comment]
Not to mention that on blizzard servers it actually *is* an instant cast through the trade window.

**Comment by Lhalyna** [comment]
i mean this is in later expansions, in tbc is enchant for other players a instant spell

i test it recently on the official tbc server / instant spell

**Comment by Naraku93** [comment]
then it's my mistake, sorry guys
