### ISSUE TITLE
NPC 17459 - Trigger NPC is visible

### ISSUE THREAD

**Issue by insunaa** [cmangos/tbc-db#951]
NPC 17459 is a trigger-bunny that's supposed to be invisible, but missing the invisibility extraflag

```sql
UPDATE creature_template SET ExtraFlags=128 WHERE entry=17459;
```
screenshot is with .gm on because I already fixed it in my database so I can't show without gm mode anymore :grimacing: 
![image](https://user-images.githubusercontent.com/3718129/132884330-5ff918c4-9257-40c7-ae70-6451f1de0cff.png)

**Comment by killerwife** [comment]
The real fix is never to use that flag 99% of the time. Its usually model change and unselectable unit flag

**Comment by insunaa** [comment]
fair enough. the unit does have unselectable flag, but I wouldn't know which model to use, so this was the easiest solution known to me

**Comment by AnonXS** [comment]
[3] UNIT_FIELD_FLAGS: 33554432

modelid2 seems to should have probability = 0, which we cant do atm.
