### ISSUE TITLE
Quest 3379 - Shadoweaver - missing afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#961]
The big infernal says a text either as afterscript or as he despawns.

**Comment by killerwife** [comment]
Also check if raze gives staff of command for controlling him.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/3e35c126448d6738e5894f9e5f14edf12c5c79a2

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/commit/b1329af4d9d8890dd6a1b6f33c0c4d8604961100
