### ISSUE TITLE
Quest 2521 - To Serve Kum'isha - missing afterscript

### ISSUE THREAD

**Issue by killerwife** [cmangos/tbc-db#967]
In vmangos

**Comment by killerwife** [comment]
https://github.com/vmangos/core/commit/0f8ce721da882766f33e499ae7997f7a10802d1e

**Comment by miraco** [comment]
https://github.com/cmangos/tbc-db/issues/892#issuecomment-986813369
Same problem same entryid spawned multiple times with different relay script.

**Comment by Nytanath** [comment]
Fixed by https://github.com/cmangos/tbc-db/pull/994 I believe?

**Comment by miraco** [comment]
Yes
