### ISSUE TITLE
Guards summon from nowhere... 

### ISSUE THREAD

**Issue by al3xc1985** [cmangos/tbc-db#969]
@AnonXS in the human start zone, it appears many Northshire Guard in the kobold vermin camp and they seem to try to attack me when I attack the kobolds but they are just in position of attacking me, but not attacking.

they seems to spawn in the zone when I attack the kobolds... evey time I attack the kobolds they spawn
it is like a script thing...only when I attack vermin and worker type of kobolds they just spawn

**Comment by d3athbl0w** [comment]
Confirmed, I will upload photo and video

**Comment by AnonXS** [comment]
Problem was the data i recently added, made the mobs you kill in the starting area "civilian"

I reverted the whole commit as it makes no sense to keep any of it without new civilian data.

https://github.com/cmangos/tbc-db/commit/6853bbca8ef5fc9e47dd00c614e6e59afe1f8afb
